project:
  type: book
  
always_allow_html: true

book:
  favicon: favicon.png
  title: "Long-term Dynamics and Peasant Autonomy in the Italian Countryside"
  author:
  - name: Roberto Ragno
    affiliation: Dipartimento di Ricerca e Innovazione Umanistica, Università di Bari
    orcid: 0000-0002-7333-9035
    email: roberto.ragno@uniba.it

  sidebar:
    style: floating
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: "Roberto Ragno, PhD Candidate, Dipartimento di Ricerca e Innovazione Umanistica, Università di Bari Aldo Moro"
  chapters:
    - index.qmd
    - intro.qmd
    - literature_review.qmd
    - part: "Materials"
      chapters:
        - materials_archaeobotany.qmd
        - materials_zooarchaeology.qmd
    - database.qmd
    - methods.qmd
    - part: "Results"
      chapters:
        - archaeobotany.qmd
        - zooarchaeology.qmd
        - integrating_bot_zoo.qmd
    - discussion.qmd
    - conclusions.qmd
    - sites_references.qmd
    - references.qmd
  appendices:
      - functions.qmd

bibliography: references.bib
csl: elsevier-harvard2.csl

format:
  html:
    theme: cosmo
    callout-appearance: simple
  pdf:
    documentclass: scrreprt

editor: visual

