project:
  type: book
  
always_allow_html: true

book:
  favicon: favicon.png
  title: "Peasants, Agriculture, and Environment in the 1^st^ Millennium CE Italian Countryside: A Bayesian approach"
  author:
  - name: Roberto Ragno
    affiliation: Dipartimento di Ricerca e Innovazione Umanistica, Università di Bari
    orcid: 0000-0002-7333-9035
    email: roberto.ragno@uniba.it

  sidebar:
    style: floating
    tools:
      - icon: github
        href: https://github.com/robertoragno/phd
      - icon: twitter
        href: https://twitter.com/ragno_roberto
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: "Roberto Ragno, PhD Candidate, Dipartimento di Ricerca e Innovazione Umanistica, Università di Bari Aldo Moro"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
        - literature_review.qmd
    - part: "Materials and Methods"
      chapters:
        - materials_archaeobotany.qmd
        - materials_zooarchaeology.qmd
        - database.qmd
        - methods.qmd
    - part: "Results"
      chapters:
        - archaeobotany.qmd
        - zooarchaeology.qmd
    - part: "Discussion and Conclusions"
      chapters:
        - discussion.qmd
        - conclusions.qmd
    - part: "Bibliography"
      chapters:
        - sites_references.qmd
        - references.qmd
  appendices:
      - functions.qmd

bibliography: references.bib
csl: elsevier-harvard2.csl

format:
  html:
    theme: cosmo
    callout-appearance: simple
    cover-image: images/phd_cover.png

editor: visual

