# Conclusions {#sec-conclusions style="text-align:justify;"}

This research represents the first comprehensive collection of legacy plant and animal count data dated to the 1^st^ millennium CE from mainland Italy. While some syntheses presented in @sec-lit-rev exist, they lack raw data or were not available when this study commenced. One of the main motivations for this research was the lack of existing large-scale analyses of past agricultural landscapes. Although further excavations targeting specific areas or chronologies are necessary, legacy data are an invaluable source to provide preliminary trends, which can later be updated in light of new information. The results have enabled discussion on macro-trends in the distribution of economically important species, contributing to broader historical debates within ancient agricultural economy studies. Particularly, bioarchaeological data have provided empirical support to historical hypotheses and interpretations, which often rely exclusively on documentary sources and settlement pattern studies.

While the geographical and temporal scope of this research is broad, it is essential to look at the wider context in order to fully assess the factors behind transitional farming practices and farmers' responses to change. In other words, large-scale analyses allow the identification of structural changes rather than local pathways, but require large amounts of data. The extent of such changes can only be understood at a vast scale. Although there is considerable variation within the complex Italian geography, the legacy of the Roman Empire had an enduring influence on Italian economies, revealing that Roman agricultural practices persisted in different areas of the peninsula for some time after the political collapse of the Empire. Several factors have been taken into account in this research, such as cultural, geographical and environmental factors. Trentacoste and Lodwick [-@trentacosteAgroecologyRomanExpansion2023, 189] have already argued that local trajectories had a greater impact on agricultural choices in the Middle Republic than the effect of the cultural 'Romanisation' of Italy. Our research has shown that during the Roman imperial period there were some geographical differences in agricultural production, particularly in animal husbandry, but we also identified many commonalities. However, it is only in Late Antiquity and the early Middle Ages that agricultural strategies became increasingly localised and these local trajectories became more pronounced. While climatic trends may have influenced farmers' crop selection strategies, we argue that economic structures and institutions (or the lack of them) were more significant factors in agricultural change. Changes in political organisation led to restructuring of the landscape, and this is also supported by bioarchaeological data. This is not to deny the importance of other decision elements - farmers certainly had to weigh up multiple factors, all of which contributed to economic decisions and helped to minimise risk while optimising output.

In order to provide a holistic reading of the landscape, this research has not included all the predictors of interest in the same regression formula to assess which best explains the variation in the datasets. At this stage, with the amount of data available, it is more valuable to focus on simpler models that take into account issues such as differences in group size and overdispersion.

The development of specific targeted Bayesian models has enhanced the precision of estimates in terms of the probability of occurrence of certain species or categories, stratified by selected geographical (region, elevation, etc.) or contextual (chronological phase and settlement type) factors. Where the number of observations was scarce, the credible intervals offered a degree of reliability. Whilst previous reviews of historical Italian plant and animal data have mostly provided means after collation of data, these measures are not without problems. In particular, means can be misleading because of the inherent problems in the data set described in @sec-methods. The issue of class imbalance (i.e. differences in the sizes of groups of observations) was in part addressed through partial pooling in multilevel modelling, and the use of the beta-binomial distribution in modelling zooarchaeological count data tackled the key issue of overdispersion. The goal here was not to eliminate uncertainty, but to quantify it, providing honest estimations for safer historical interpretations. Rather than being reduced, the variability in the dataset was preserved, as this might also carry archaeological and historical implications. For instance, increased variability in the distribution of species in the 7^th^-8^th^ centuries further contributes to the interpretation of such centuries as a moment of change. Historical interpretations for this period are also problematic because of the paucity of assemblages dated to these centuries, which in turn results in wider credible intervals. In particular, the small number of assemblages dated to the 7^th^ and 8^th^ centuries may not be due to a specific research bias, but possibly to the dating methods used. Indeed, the use of ceramics as a dating method is problematic given the lack of standardisation in early medieval ceramic production in Italy[^conclusions-1].

[^conclusions-1]: Recently, however, the discipline has made progress in constructing more accurate ceramic chronologies, although contexts from this period often report a high proportion of handmade pottery. On this topic, cf. @arthurFormFunctionTechnology2008; @arthurCartaArcheologicaPuglia2012; @molinariInsediamentiEdEconomia2017; @uggeripatitucciCeramicaAltomedievaleItalia2004.

One of the advantages of statistical modelling is replicability, which allows for finer comparisons (between regions, chronological phases, etc.) beyond simple measures of central tendency (i.e. means, medians, etc.). Replicability also implies methodological transparency, which means that other researchers can reproduce our findings, as the code and dataset used in this study are publicly available on a [GitHub repository](https://github.com/robertoragno/phd/).

However, both modelling in general and this research have certain limitations. Archaeology, like any social science, is inherently inexact [@smaldinoModelingSocialBehavior2023, 11]. Archaeological data can be used in models of social behaviours (such as what to grow and raise on a farm), but the data itself is only a proxy for the actual information we want to discuss. For example, the number of cereal caryopses that have been preserved in a waste pit rather than the amount of cereal grains that were produced in a given chronology. Models, while allowing for generalisations, often have low geographical and temporal resolution, especially for phases traditionally grounded in documentary sources, leading to a scarcity of radiocarbon dates and bioarchaeological samplings. While credible intervals and precision parameters provide a degree of reliability, the chronological uncertainty in the available assemblages remains one of the foremost issues in the dataset. Future research should explore methods to either address this issue or quantify the bias it introduces into estimations.

The reliance on generalised models in archaeological research, while beneficial for large-scale analysis, can potentially obscure micro-histories. The landscape of the Italian peninsula, broadly divided into coastal plains, hills, and mountainous areas across its three subregions, is also characterised by several micro-climates. These distinctions are crucial to understanding the history of the Italian landscape and its place in the wider Mediterranean context. We need to move towards quantitative studies that can adapt to different scales, capturing both the macro and micro aspects of the landscape. To work effectively at these different scales, a larger dataset is essential. The ongoing efforts of 'global' landscape archaeology projects across Italy are invaluable in this regard, as they contribute significantly to data collection. Areas with denser information will enable more sophisticated spatial studies, thereby improving our understanding of past cultural landscapes.

The dataset's spatial biases stem from varying levels of effort in studying botanical and faunal remains. The availability of data in certain geographical areas appears to be closely tied to the dedication of particular research teams. For example, the abundant archaeobotanical data from the Po Valley can be attributed to the targeted work in that area of the palaeobotany laboratory at the University of Modena. Similarly, the University of Salento's efforts have resulted in rich data from Puglia. The area of Rome is particularly rich in studies of faunal remains (largely due to the work of De Grossi Mazzorin), while virtually no archaeobotanical study has yet been published with data from the capital. Although certain geographical areas may be more conducive to the preservation of organic material, the survey indicates that our attention should be directed towards specific regions. It is striking that for the first millennium there is very little (if any) evidence of environmental archaeology in Calabria, Umbria, Marche, Friuli Venezia-Giulia and Valle d'Aosta. Ideally, future excavations in Italy will also need to better integrate the professional figures of archaeobotanists and zooarchaeologists at the stage of the research design itself, to promote more efficient sampling strategies that permit a more thorough coverage of the site.

In addition to the temporal and spatial biases in the dataset, which necessitate more archaeological excavations to fill these gaps, future research should also place specific focus on underrepresented settlement types. While urban sites and smaller rural settlements are well represented, the number of small 'peasant' sites is still low. Initiatives such as the 'Roman Peasant Project' [@bowesRomanPeasantProject2020] have started addressing this gap, but archaeological and behavioural studies of marginal social strata is arguably still at an early stage. Complementing data with other archaeological evidence, such as olive and wine presses, ceramics, agricultural storehouses, and biometric data (e.g. size, age, and sex information), is crucial for developing better historical models. This was not possible due to time constraints.

Finally, a quantitative approach to model counts (which was not possible, as seen in @sec-methods, for archaeobotanical remains), particularly for archaeobotanical remains, and small-scale approaches to quantify agricultural yields[^conclusions-2], are essential for drawing more reliable and substantial conclusions about production and trade.

[^conclusions-2]: cf. @goodchildGISModelsRoman2013; @witcherAgriculturalProductionRoman2016; @witcherModellingAgriculturalLandscapes2010; @pinchetti2021

The field of environmental archaeology is growing in Italy, with interesting results that move away from interpretations based solely on historical literature. Although some limitations need to be overcome with targeted studies and excavations, the potential for reconstructing historical Italian landscapes is vast. Indeed, the increase in the number of data available and the quality of the publications can bring many advantages in terms of the type and precision of the statistical analyses at our disposal. For example, future studies will be able to model the spatial distribution of specific plant and animal species more accurately, which was not possible here due to these limitations and the research agenda of this assessment.

This project has raised several issues that need to be addressed in future research. The integration of archaeobotanical and zooarchaeological data has proved useful in reconstructing ancient agricultural strategies, but we must be careful about the significance of the proxies used. In the case of botanical remains, these are mostly preserved by carbonisation in Italy (cf. @sec-materials-bot) and inevitably obscure fresh produce, which was not commonly stored. The recovery methods used in most excavations also dictate the composition of the faunal assemblages, and we suspect that water resources (marine or freshwater) and birds may have contributed more to the diet than our models show. Again, this evidence needs to be combined with other (archaeological and bioarchaeological) proxies to infer dietary practices and human mobility. Recent projects are moving in this direction, for example by compiling large sets of isotopic data that will need to be integrated into future analyses [@cocozzaPresentingCompendiumIsotoporum2022].

Overall, this research has also shown that the time is ripe to make generalisations of the Italian bioarchaeological data for historical periods that already exist or are in progress for other European regions. As a first step towards this goal, this project is also relevant because it will allow comparisons with other areas of the continent. Agricultural practices are not only dictated by environmental or market requirements; farmers are active agents in shaping the landscape and their actions are charged with cultural elements and individuality. With this in mind, we hope that future bottom-up research will recognise the agency of farmers and identify common trends in their responses to change. Finally, we also trust that this research will encourage new excavations to fill in the grey areas in the scholarly literature.
