# Discussion {#sec-discussion style="text-align:justify;"}

This study examined the complex relationship between subsistence patterns, economic activity, and environmental changes in relation to regional patterns of Italian peasantry in the 1^st^ millennium CE. The area experienced significant changes, moving from a coordinated agricultural market system during the imperial era to a more localised market structure following the political disintegration of the Western Roman Empire. During a period of political and demographic changes, as well as fluctuations in the climate, the settling of Germanic migrants on the peninsula probably also had an impact on land management and production systems. While acknowledging that numerous factors may have played a role in such a complex phenomenon, the results of this study aim to advance the current discourse on the agricultural history of the first millennium by examining specific themes, using accessible archaeobotanical and zooarchaeological data. This study takes a macro-level approach, contrasting with the more local or regional studies typically conducted in this area. The primary focus is on potential production or consumption patterns, based on the available data and methods used. This work is one of the first efforts to construct a comprehensive bioarchaeological database covering a substantial spatial and chronological range in Italy.

The goals of this research were:

1.  **Assessing diversification in Italian historical agriculture**: The inquiry focuses on discerning the level of diversification in historical agricultural practices across Italy. Periods of increased diversity in production and consumption are investigated to gain insights into subsistence practices and mixed-farming strategies.

2.  **Analysing factors influencing the distribution of plants and animals**: The study systematically evaluates the impact of various factors on the distribution of plants and animals. Environmental samples are stratified based on chronology, context type, Italian sub-regions, altitude, temperature, and other pertinent parameters.

3.  **Reconstructing the Italian historical farming landscape and food consumption**: The main aim is to reconstruct the agricultural landscape in Italy and analyse food consumption patterns. The approach taken is comprehensive, striving to grasp the interconnectedness between environmental variables, societal shifts, and farming methodologies. This reconstruction employs both a quantitative and qualitative approach, contrasting the results with the current debate on the subject.

This study's analysis of animal and plant remains from numerous archaeological sites shows that the main domestic crops and livestock of the first millennium were identical to those of the Bronze Age and Republican periods [@bernardEnvironmentalClimateHistory2023]. These included cereals, pulses, fruits, particularly olives and grapes, and domesticated animals, such as cattle, pigs, sheep, and goats. What did change though is the relative significance of these species during various time periods, and this is what we sought to model. Additionally, certain food plants were introduced during the first millennium CE, which have not been modelled separately due to being beyond the scope of this study and requiring targeted methodologies. For example, the database includes records of various exotic species such as melons, dates, and peaches. However, these species are aggregated into macro-categories like 'domestic fruits' as our focus is on plants that have a more significant contribution to the economy. In this context, it is clear why the study incorporated specific animal and plant species into the same model on account of their rarity or marginal role in the wider economy. For instance, wild fauna has been integrated into a single model to capture overall game access, and groups of common/uncommon fruits and nuts have been modelled together for the same purpose. Such macro-groups do not, however, include olives and grapes.

This discussion will consider the significance of specific results as they pertain to broader debates in agricultural history. We will first consider cereals, as they were staples of the ancient Italian diet and a large sector of the agricultural economy. In addition to cereals, other plants are considered including -- legumes, olives and grapes, other fruits and nuts. The focus here is on economically significant plants. Secondly, we will examine the four main domesticated animals and only present general chronological overviews for other animals. Finally, we will present brief hypothetical reconstructions of the Italian agricultural landscape in four temporal phases to integrate the results and discussion.

## Plant cultivation

### Cereals

In antiquity, the Italian diet relied heavily on cereals, which provided a significant source of immediate calories due to their high carbohydrate content [@grivettiMediterraneanFoodPatterns2001; @purcellWayWeUsed2003; @brownGrainPulsesOlives2011]. As highlighted in @sec-lit-rev, Rome was one of the largest "grain states" in history [cf. @scottGrainDeepHistory2017]. The city had a high demand for grain, which was partially met through imports from Africa and Egypt during imperial times [@jamesFoodProvisionsAncient2021, 21].

This research presents evidence for the local cultivation of several cereal species. Additionally, it offers insight into the practice of mixed farming during the Roman period. This insight serves as a starting point for gaining a better understanding of the farming practices employed in Italy during the first millennium CE. While previous research [@spurrArableCultivationRoman1986] had already suggested that Roman agriculture was not based solely on the monoculture of naked wheats, more recent archaeobotanical evidence has confirmed this, showing that several types of cereal were grown in a variety of settings, including villas, small settlements and close to urban centres. Among these cereals, the most common in the archaeobotanical assemblages in the Roman period (ranging from the 1^st^ century BCE to the 2^nd^ century CE) were free-threshing wheat, barley and emmer. In addition to these species, other more rustic cereals -- including two types of millet (*Setaria italica* and *Panicum miliaceum*) and einkorn wheat (*Triticum monococcum*) -- were cultivated. In particular, proso millet (or 'common millet', *Panicum m.*) was especially prevalent in the south.

In @sec-lit-rev, we discussed the widespread idea that hard wheat gradually superseded emmer [@heinrichModellingCropSelectionRoman2017, 143; @heinrichCerealsBread2019, 104; @lentjesPlantingSeedsChange2013; @thurmondHandbookFoodProcessing2006, 20; @moritzGrainMillsFlourClassical2002]. Emmer was a staple in archaic Rome and was used in preparing *puls*, a porridge-like soup [@thurmondHandbookFoodProcessing2006, 29]. It is difficult to determine precisely when emmer was replaced by naked wheats. This study shows that this variety of grain was not as widespread as free-threshing wheats, but it was not entirely abandoned either. On the contrary, emmer seems to be increasingly present in a greater number of sites during the later chronological phases. However, although the presence of emmer increases, from a quantitative perspective its abundance seems to decrease over the course of the 1^st^ millennium CE.

While some authors argue that emmer was the dominant hulled wheat variety cultivated in Roman times [@whiteCerealsBreadMilling1995, 39; @murphyFindingMilletRoman2016, 67], our research reveals a different perspective. In fact, barley, another husked cereal, was more widely cultivated and abundant. The Romans considered barley to be an inferior grain -- a negative perception that dates back to at least the 3^rd^ century BCE -- mainly because it was less suitable for breadmaking due to its low gluten content. The gluten content is further reduced by roasting to remove the husk. For these reasons, barley was traditionally considered more suitable for making porridge [@thurmondHandbookFoodProcessing2006, 17-18].

Despite this perceived inferiority of barley, our results show that barley consistently competed with free-threshing wheat in 1^st^ millennium CE assemblages, and was even more common and abundant in early medieval and 11^th^-century samples.

The data presented here cannot provide precise information regarding agrarian production, given that botanical remains alone do not provide insight into the local or imported provenance. To improve understanding, this information should be integrated with other archaeological features such as storage facilities, wine and olive presses, and soil analysis. Nevertheless, the distribution of plant species across site types and regions serves as a useful proxy for understanding agrarian economic trends.

During the Roman phase, free-threshing wheats and barley were predominant in rural sites, but less common in urban and villa sites. The reasons for this difference in the distribution of naked grains will be examined later in this chapter. On the other hand, it is interesting to note that the distribution of the so-called 'minor' grains is almost identical in all three site types. Geographically, free-threshing wheats and barley show similar patterns throughout Italy in the first phase of the study, with marked differences in the cultivation of other cereals. Geographical disparities do appear, but only in relation to altitude. Further observations show that northern Italy, even in Roman times, favoured, to a small extent, more rustic cereals compared to central-southern Italy, where their presence was limited. This trend is in line with later historical developments, indicating a greater reliance on free-threshing wheat and barley in the south, while northern and central Italy cultivated a more diverse range of cereals.

These findings are quantitatively supported by both our Bayesian models and a frequentist case study. In particular, the latter highlights that the distinction between northern and southern Italy - in terms of cereal cultivation - only became pronounced in the early medieval period, with Roman agricultural practices showing less significant regional variation. These findings do not necessarily confirm the link between Roman farming practices and the cultivation of a single crop. During the Roman phase, fewer crops were grown, resulting in the lowest plant richness score. At the same time, however, there was a good degree of diversity in the plant species present, indicating that no single crop dominated the assemblages to an extent that would indicate monoculture or the absolute consumption of a single plant.

Moving into the early medieval period, our findings show that other important actors arose in the Italian countryside -- the military elites located in fortified sites. While we know from the historical record that these actors might have played a significant role in influencing agriculture, there are few settlements of this type that have archaeobotanical data associated with them. Every fortified settlement recorded in our dataset, spanning from the late Roman to the medieval period, is located in Central and northern Italy, where the phenomenon of *incastellamento* first took hold. Despite the number of assemblages available, these sites have one characteristic in common, namely the necessity for large storage units for cereals and other agricultural goods. Free-threshing wheats and barley, with a variety of other cereals, legumes, grape remains, are present in these locations in large numbers, sometimes even more so than in rural sites. The geographical bias in the dataset towards the centre-north probably also conditions our interpretation, since it is in these regions that the archaeobotanical contexts are richest in plant species.

The botanical richness and abundance of remains in these sites can be mapped to the historical literature that discusses the ways that these sites would function in relation to their food storage. Military sites had to guarantee a food supply for their soldiers and those who were offered protection in exchange for taxes, which were often at a partial rate in these territories.

At the fortified settlement of Monte Barro, situated in Lombardy's pre-Alps, a sizable 7.20 x 9.60 m room, referred to as 'room f', was likely utilised as a cereal storage facility during the 5^th^ and 6^th^ centuries [@castellettiRestiVegetali1991; @brogioloArcheologiaMonteBarro1991, 37-9]. A substantial food processing and storage zone is visible in the 10^th^-11^th^ century phase at Sant'Agata Bolognese, an early medieval fortified rural village [@bosiAlimentazioneAmbienteVegetale2014, 318]. Finally, a similarly well-documented case is observed at Miranduolo Castle, which had silos in the same era that demonstrated excellent separation between various crops. This site also displays a degree of centralisation, with the largest pulses and cereals being stored within the manor court barns. @buonincontriFarmingRuralSettlement2014 also investigated the dimensions of *Triticum aestivum/durum* at Miranduolo, indicating a rise during this stage in contrast with the preceding phase.

+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
|                           | Peveragno, loc. Castelvecchio               | Monte Barro                   | Loppio, isola sant'Andrea      |
|                           |                                             |                               |                                |
|                           | (3^rd^-6^th^ c.)                            | (5^th^-6^th^ c.)              | (5^th^-6^th^ c.)               |
+:==========================+:============================================+:==============================+:===============================+
| *Triticum aestivum/durum* | 26.5%                                       | 92%                           | 0.3%                           |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
| *Hordeum vulgare*         | 1.3%                                        | 3%                            | 6.7%                           |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
| *Secale cereale*          | 63.7%                                       | 3%                            | 1.3%                           |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
| *Other cereals*           | 8.5%                                        | 2%                            | 91.7%                          |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
| **Context**               | Occupation levels, small oven, hearth       | Storage                       | Hearth, occupation levels      |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+
| **Reference**             | @motelladecarloIVIndaginiAntracologiche1995 | @castellettiRestiVegetali1991 | @moserRicercheDiCarpologia2006 |
+---------------------------+---------------------------------------------+-------------------------------+--------------------------------+

: Examples of *castra* dated between the 3^rd^ and 6^th^ centuries.

+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
|                           | Rocchette Pannocchieschi                | Sant'Agata Bolognese                   | Miranduolo                               |
+:==========================+:========================================+:=======================================+:=========================================+
| *Triticum aestivum/durum* | 98%                                     | 32%                                    | 35%                                      |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
| *Hordeum vulgare*         | 1.4%                                    | 7%                                     | 9%                                       |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
| *Secale cereale*          |                                         | 0.25%                                  | 29%                                      |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
| *Other cereals*           | 0.6%                                    | 60.75%                                 | 64.7%                                    |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
| **Context**               | Occupation levels                       | Storage                                | Storages                                 |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+
| **Reference**             | @buonincontriFarmingRuralSettlement2014 | @bosiAlimentazioneAmbienteVegetale2014 | @buonincontriMultiproxyApproachStudy2017 |
+---------------------------+-----------------------------------------+----------------------------------------+------------------------------------------+

: Examples of fortified settlements dated between the 10^th^ and 11^th^ centuries.

From these trends, it is evident that naked wheats did not completely replace husked wheats and other grains during the Roman age and beyond. There are various potential justifications for the cultivation of more rustic grains. Kron [-@kronRomanLivestockFarming2004, 128] argued that ancient farmers were likely aware of the nutritional benefits of feeding hulled grains to their livestock, if cereal straws were often used as animal feed. Columella (*Rust.*, VI, 3, 3), for example, recommended millet (a C4 plant) as cattle feed.

The presence of millets in archaeobotanical samples is sometimes associated with the diet of low status individuals or with animal feed [@killgroveDietCollapseStable2018], but this association is controversial [@murphyFindingMilletRoman2016] and should be treated as such. The role of C4 plants in the northern Italian diet is documented through isotopic analyses [@cocozzaPresentingCompendiumIsotoporum2022]. Additionally, @ganzarolliDirectEvidenceLipid2018 disproved the assumption that millets were solely consumed by the lower strata of the population. They applied lipid residue analysis to cooking vessels dating from the 6^th^ to 10^th^ centuries, which showed that millets were present in both high-status and low-status contexts in Padua.

Millet are often under-represented in samples due to their small grain size. Their short growing season, which lasts only three months, allows them to be planted between crop cycles, reducing the risk of famine in the event of poor harvests. Therefore, millets are often considered a marker of ley farming and crop rotation [@spurrArableCultivationRoman1986, 94-101]. Indeed, Pliny the Elder (*HN*, XVIII, 23) reports that in the Campanian fields millet was sown in alternation with emmer [@murphyFindingMilletRoman2016, 68].

Furthermore, barley and millets can withstand drought, which would have made them especially beneficial in southern regions with little annual rainfall like *Apulia* and *Calabria* [@crespi19611990HighresolutionMonthly2018]. During the Roman period, proso millet was a popular cereal in southern Italy, found on 42% of the studied sites. Upon closer inspection of the sites leading this trend, it is clear that Pliny's claim (*HN*, XVIII, 24) that "millet thrives in Campania" is supported by the archaeobotanical evidence. The places where millet is found in the Roman period are situated in the regions of modern-day Campania and Basilicata. These include multiple spots within Pompeii and Herculaneum, as well as in Pantanello. Millet's suitability to grow in specific climates is debated. Philip Jones [@jonesItaly1966, 100] stated that millet can only grow in wet regions such as the Po Valley, the Alps, and some parts of Campania. However, the results of the archaeobotanical study indicate that millets are also found in different regions, and studies have indicated that they grow best in arid climates, as extended contact to water might harm the plant as well as its output [@carusoResponsesDifferentPanicum2018]. To assess this, we tried using current yearly rainfall to predict results in our models, but the results were not better than using altitude. With more data on both dry and wet regions, future models may be able to use this variable more fruitfully.

Other cereal crops, in addition to millets and barley, can withstand harsh soil and weather conditions. Some of these crops are also highly nutritious, despite their lower levels of gluten and carbohydrates [@buonincontriMultiproxyApproachStudy2017]. For example, rye was more frequent in early medieval central and northern Italy, and einkorn (*Triticum monococcum*), which was commonly cultivated throughout the 1^st^ millennium in central and northern Italy (often planted on hills).

There has been substantial scholarly discussion regarding the reasons behind the growth in rye consumption in late Roman Italy, with several explanations proposed. Some have argued that the Lombard migrations of the late 6^th^ century introduced a preference for rye in Italy[^discussion-1], while others attribute the cultivation of this grain to the cooling trend of the 6^th^ and 7^th^ centuries. Rye is a winter crop that can resist both frost and drought [@mccormickWhatClimateScience2013], making it a valuable resource in the difficult agricultural conditions of the time. These qualities help clarify why, during the early medieval phase, our altitude-based models indicated a higher likelihood of finding rye at high altitudes. Prior to this research, a study of archaeobotanical evidence from 3^rd^ century BCE to 6^th^ century CE in northern Italy also reported an increase in the frequency of *Secale* from the 3^rd^ century CE [@bosiArchaeobotanicalEvidenceFood2020, 692]. The trend is confirmed by our mean relative ranks, which increase sharply after the Roman period.

[^discussion-1]: cf. @behreHistoryRyeCultivation1992 for a history of the spread of rye in Europe.

Rye was not the only type of cereal to become more common after the Roman period. Other rustic grains were more ubiquitous and abundant in both rural and urban areas, with a steep rise in the early Middle Ages. In addition to their ability to withstand adverse weather conditions, husked grains may have become popular because of their longer shelf life. The husk protects the caryopsis from pests and bacteria, increasing its durability. This would have been especially beneficial to small farmers or tenants who may not have had access to more advanced storage facilities. All these circumstances may have encouraged small farmers to sell their surplus naked wheat on the market. Cereals offered greater market security, at least locally, than other products such as olives and grapes, which faced higher external competition. Furthermore, the initial establishment of olive groves and vineyards demands significant upfront investments before yielding profitable returns [@heinrichModellingCropSelectionRoman2017].

Although environmental, political, and economic factors, in addition to the cultural influence of new settlers, had a role in the rise of rustic cereals in central and northern Italy during the early medieval period, it is important to consider the ways in which these cereals mitigated risk for farmers. By being less labour intensive, more durable, and quick to grow, 'minor' grains would have been a safe investment for farmers at the time [@squatritiRyeRiseRome2019] - especially for feeding the household.

This discussion begs the general question: what factors contributed to the different agricultural strategies observed in early medieval southern Italy compared to the north? Although there are limitations to this research (which will be considered further in the conclusion), it is possible to propose some explanatory theories from the results of this study.

First, the different agricultural situation in early medieval southern Italy can be thought of in terms of the strong focus that the region had on cereal agriculture, as previously noted by Masssimo @montanariAlimentazioneCulturaNel1988.

While textual sources from this period scarcely mention crops with precision, the few documents dated before 1000 CE reveal the commercial and urban nature of the south, with *frumentum* (wheat) still being used as currency in transactions. Although *ordeum* (barley) is occasionally referred to, other grains are rarely mentioned in the transactions documented in the historical literature from this period [@montanariAlimentazioneCulturaNel1988, 125-130]. The lower prevalence values of husked cereals in the southern regions of Italy point to a shift in farming practices that started at least in the 3^rd^ century CE. The only grain that is consistently seen throughout all phases is emmer, which was common in Roman times and never died out.

These changes must be seen in a wider historical context. The *annona* imports from Egypt, which had previously been sent to Rome, were probably diverted to the new centre of power, Constantinople, which became the new capital of the Roman Empire in 330 CE. This left mainland Italy without a major production centre, meaning that southern landowners, especially those with *massae fundorum*, would have increased their production of naked wheats [@volpeContadiniPastoriMercanti1996]. @volpeLineeDiStoria2001 describes this as the 'wheat march', in which the vast *Tavoliere* region of northern Puglia, with its large areas of land suitable for extensive agriculture, would have been a prime location for an increase in production. The production of wheat in *Apulia* and *Calabria* later reached its peak in the mid-5^th^ century, following the Vandal invasion of North Africa, resulting in the emergence of a "late antique agrarian system" [@volpeContadiniPastoriMercanti1996].

The effects of the reorganisation of production following the transfer of the capital to Constantinople are evident in the archaeological record. First, much of the North African grain was transported to Italy in ceramic vessels, the number of which gradually decreased before disappearing in the 7^th^ century [@arthurRomanCommercialAmphorae1997; @deloguStoriaEconomicaDi1993]. Secondly, our results confirm the intensification of wheat production in the south, a trend that continued throughout the early medieval period (6^th^-10^th^ century CE) and even beyond. In contrast, the diversity in northern Italian archaeobotanical assemblages seems more indicative of small-scale farming. In this regard, @wickham2005 hypothesised that certain cereals, such as millet and rye, experienced an increase in popularity in central and northern Italy due to the growing decision-making autonomy of farmers. This type of agriculture is also compatible with urban gardening, as intensive production techniques were gradually introduced in more urbanised areas [@goodsonCultivatingCityEarly2021; @goodsonGardenCitiesEarly2018]. Despite these changes in the north, southern Italy remained dominated by free-threshing wheats, barley, and emmer.
The almost complete disappearance of husked wheat varieties in the south and the concentration on the cultivation of naked grain can be attributed to the need to feed Rome after the disruption of the *annona* system. This hypothesis is also supported by the significant investments made by the Roman aristocracy in the south during this period, in particular the investment in storage structures at the villa of Faragola (Ascoli Satriano) and other buildings related to the stocking and processing of cereals [@volpeEconomiaCommerciInfrastrutture2023, 621].

The fragmentation of cereal production across regions was not a phenomenon unique to Italy. Jean-Pierre @devroeyNatureRoiEnvironnement2019 outlines a division between southern and northern cereal cultivation more broadly in Europe after the year 1000. In this analysis, there seems to be an "old" rotation of barley and free-threshing wheats in southern Europe, and a "newer" rotation that alternated free-threshing wheats, oats, rye, and barley. If we accept this hypothesis, this would imply that temporally, geographically, and contextually uneven cereal trends in Italy from the Roman to the early medieval period were consistent with a broader fragmentation occurring on a European scale.

### Legumes

Although cereal and cash crops dominate the discussion of ancient agrarian economy, legumes were an important addition to the range of cultivated plants in the first millennium. Among the cultivated pulses, the species of the genus *Vicia* were particularly predominant. This includes *V. faba minor* (fava beans), *V. sativa* (common vetches), among others. Other common pulses in the Italian contexts include garden peas, grass peas, lentils and chickpeas.

In the Roman period, legumes were widely cultivated throughout Italy, with a slight predominance in the southern regions where *Vicia* sp. pulses were especially common. Legumes are particularly present in religious settings, likely used as ritual offerings. For instance, a 1^st^ century BCE offering in Pompeii's shrine at domus VI, 1, 13 included four types of legumes, and a 1^st^ century CE layer revealed five different species [@murphyRomanFoodRefuse2013]. Similarly, three pulse varieties were found in a 1^st^ century BCE ritual offering in the garden of Amarantus's domus in Pompeii (I, 9) [@robinsonDomesticBurntOfferings2002]. Pulses were a frequent find in Roman funerary and other ritual contexts, a fact supported by our models. This is also evidenced in several cremation sites across Italy and Europe [@boubyFruitsSeedsRoman2004; @matterneFrancoItalianInvestigationFunerary2008; @vazFoodDeadFuel2021; @rottoliPlantOfferingsRoman2011; @reedExploringRomanRitual2019].

Beyond these ritualistic uses, legumes were found in urban, rural, and villa sites alike. While their presence slightly decreased in urban settlements during the late Roman period, the estimated mean remained relatively stable in rural sites and villas. In fact, legumes played a significant role in agriculture due to several reasons. As highlighted in @sec-lit-rev, legumes are fundamental to crop rotation because of their nitrogen-fixing qualities. Although the scientific understanding of this came much later, Romans recognised that legumes helped to replenish soil depleted by cereal cultivation [@flint-hamiltonLegumesAncientGreece1999, 373].

Legumes were also valued as good emergency crops because of their short growing cycle, useful if autumn-sown crops failed [@erdkamp2005, 73; @erdkampFamineHungerRoman2019, 298]. In a mixed-farming setting, legumes also served as excellent animal feed, with fava beans, grass peas, and vetches being the most common feeds [@jonesRoleForageLegumes1990]. Some pulses, like fava beans, had dual purposes: they were dried for human consumption, and their pods were used as animal feed [@flint-hamiltonLegumesAncientGreece1999, 380; @zoharyDomesticationPlantsOld2012, 102].

Finally, the Romans were also likely conscious of pulses as a valuable source of protein and appreciated their nutritional properties. This awareness is evident in urban dietary patterns, where pulses were an integral component. However, the elite often associated legumes with the diets of poorer social strata, although they still consumed them as indicated by our results and documentary evidence [@brownGrainPulsesOlives2011; @witcherAgriculturalProductionRoman2016, 468; @garnseyFeveSubstanceSymbole1992; @corbierBroadBeanMoray2013]. The high presence of pulses in late Roman and early medieval *castra*, alongside cereals, further emphasises the role of pulses as a readily available and storable source of protein.

In both rural and urban sites, there was a notable increase in legume consumption during the early Middle Ages. While in the Roman period, pulses were sometimes added to flour to make a denser, heavier bread known as *lomentum* [@flint-hamiltonLegumesAncientGreece1999, 372], in the early medieval period, they were likely more commonly consumed in soups. Although our data cannot confirm this shift, it is supported by changes in ceramic evidence. For instance, there was a rapid increase in the number of *olla* types (rounded vessels) from the 5^th^-6^th^ century, indicative of a transition to boiled dishes [@giovanniniNatalitaMortalitaDemografia2001, 68-69; @giovanniniArcheologiaDemografiaItalia2002, 77]. The rise in legume cultivation of this period, particularly in central Italy, persisted in the 11^th^ century. The 11^th^-12^th^ centuries marked the beginning of the agrarian revival, during which legumes were effectively integrated into the three-field system [@montanariStoriaMedievale2014, 83].

### Olives and grapes

In addition to cereal crops, this research demonstrates the economic significance of two other constituents of the Mediterranean triad, namely olives and grapes. The first evidence of consumption and production of olives and grapes in Italy dates back to the 2^nd^-1^st^ millennia BCE [@buonoIntroduzioneDiffusioneVite2002; @mercuriOleaJuglansCastanea2013; @magriHoloceneDynamicsTree2015]; at the beginning of the 1^st^ millennium CE the production of oil and wine is attested throughout the peninsula, as evidenced by archaeological sources including presses, *palmenti* (treading floors), and other facilities [@rossiterWineOilProcessing1981; @caracutaOliveGrowingPuglia2020; @doddArchaeologyWineProduction2022; @doddSpectacleProductionRoman2023]. We can thus be confident that both species were fully domesticated in our period of interest, and we can consider the botanical remains as indicative of production/consumption patterns.

The cultivation of vineyards and olive groves depends on certain geographic conditions, with similar requirements in terms of altitude and climate. This similarity was evident in our models, as the best conditions for both crops involve lower altitudes and milder, warmer temperatures. In particular, the distribution of olive pits seems to be especially sensitive to environmental factors. The correlation between higher elevations and a lesser presence of both crops is more pronounced during the Roman and late Roman phase, and not as apparent in later phases. This could indicate that in earlier periods mountain communities were more dependent on imports of oil and wine from more suitable production areas, while in the early medieval period production had to be reorganised to be more local. To provide additional evidence for this hypothesis, a review of how wine and oil amphoras were distributed at different elevations is necessary, even though it has not yet been explored in current archaeological literature.

In our database, settlements with palaeobotanical samples from high elevations and the lowest mean temperatures are prominently situated within the Alpine region. We can therefore anticipate stronger markers for olive and grape growing in southern-central regions, or the Po Valley in the north, where extensive excavation and sampling have been undertaken. On this matter, Roman and late Roman textual sources reveal high yields in the large plains of the Po region, particularly for wine; after all this area was part of the *Italia Annonaria*, that had to supply the capital and, importantly, the army stationed outside the peninsula [@piniViteOlivoNell1990, 337]. In fact, although in the Roman period both cash crops are most prevalent in the southern regions (especially olives), they decrease during the transition to the 3^rd^ century CE, but the presence of grapes remains stable in the north.

The analysis of the trends in central Italy is more difficult. As the available late Roman sites in central Italy (listed in @tbl-late-roman-centr-it-bot-sites) are very few and the resulting credible intervals are wide, a qualitative approach to our interpretations may be useful. Most of the archaeobotanical assemblages, dated between the 2^nd^ and 6^th^ centuries CE, are mostly located in the present-day region of Tuscany. Among these, the well-known case of the villa of Settefinestre, southern Tuscany [@jonesRestiVegetali1985]. The excavation report only lists the plant species that have been found, without providing quantitative information or a clear separation of phases. In the Roman period, the villa certainly produced both oil and wine, as evidenced by the presses. The chronology of the late Roman layers is not clear, and the more precisely dated layers are earlier than the third century. On this basis, it is not possible to be more precise, but judging by the size of the villa and the artisanal and agricultural activities associated with it, it is likely that production at Settefinestre was substantial.

Two other sites, dated between the 2^nd^ and 3^rd^ centuries, are located not too far from Settefinestre. The first, Volterra, is an urban sites where archaeobotanical samples have been taken from dark earth layers, which would suggest that agricultural activities may have taken place within the city's walls during this period. The assemblages do not record olives or grapes, although the sample size is very small (as is often the case with this type of archaeological sediment) and does not allow us to generalise [@mottaPaesaggiDiVolterra1997]. The second site, Marzuolo, is a small farmhouse. Both olive trees and vines are attested here through carpological and pollen studies. The excavators, taking into account the other archaeological finds, suggest that small-scale trade took place in Marzuolo, probably in oil and wine [@bowesRomanPeasantProject2020].

In the same period, another rural site near Marzuolo, Case Nuove, reported the abandonment of a wine press. Archaeobotanical evidence from Case Nuove is only available for the 4^th^-5^th^ century, which show however that grapes and olives were transported here in Late Antiquity, while pollen indicates that olives were grown about 1 km from the site [@bowesRomanPeasantProject2020; @mercuriCaseNuoveBotanical2020]. The small-scale production of wine is also documented from another 5^th^-6^th^ century farmhouse near Volterra. This farm probably practised mixed farming, with cattle providing manure to be used for growing cereals and vines [@mottaPaesaggiDiVolterra1997; @mottaSitoRuraleNel1993]. Unfortunately, our database does not include any other site dating back to this period, with the exception of the so-called *Schola Praeconum* in Rome, where only one grape seed was found dating back to the 5^th^ century [@whitehouseScholaPraeconumCoins1982].

To our knowledge, only one late antique villa site with archaeobotanical remains has been excavated in central Italy. The site, Villamagna, is situated in the present-day region of Marche and reports large quantities of processed grape and olive remains from a room in the *pars urbana* during the 5^th^ century.

As this information is preliminary and unpublished^[cf. @carmenatiRomanVillaVillamagna2019; @carmenatiRomanVillaVillamagna2021], Villamagna has not been included in the database. With the exception of the small sample from the *Schola Praeconum*, the total absence of archaeobotanical samples from the area surrounding Rome and Latium is striking. This absence affects all the periods under consideration, and is particularly noticeable in view of the vast number of zooarchaeological samples studied in the capital. Given this critical absence, it is not possible to comment on potential productive reorganisations in this area during the late empire. The few available sites from central Italy dated between the 3^rd^ and 6^th^ century do seem to indicate that the types of crops cultivated does not change drastically: olives and grapes are cultivated, although at a small scale, which is in line with the size of the farmhouses from where the samples have been collected.

|Site|Chronology|Context|Notes|Reference|
|:----|:----|:----|:----|:----|
|Settefinestre, Phase 2|2nd-3rd century CE|rural villa, wine pressing area|The report did not contain any quantitative information. The chronology is also uncertain and is more reliable from the early to late 2nd century, with the 3rd century levels being more ambiguous. Grape remains were found near a pressing area, olive remains are attested in the earlier phase but not in the present one.|@jonesRestiVegetali1985|
|Volterra, Vallebuona|2nd-3rd century CE|urban, dark earths|The stratigraphic layer from which the samples have been taken are dark earths, which can be associated with agricultural activities within the city in this period. The sample is very small and did not yield any grape or olive remains.|@mottaPaesaggiDiVolterra1997|
|Marzuolo, Phase 3|Late 2nd - early 3rd century CE|small farmhouse|Grape and olive macroremains, in combination with pollen analyses, attest to the probable local production of wine and oil. The authors also argue for small-scale exchange.|@mercuriMarzuoloBotanicalMaterials2020|
|Case Nuove, Cinigiano, Phase 2|Late 4th - mid-5th century CE|rural, fill of square pit (rubbish tip)|While a possible communal wine press was in use in the Late Republican period, it was abandoned in the Augustan/Tiberian period. Archaeobotanical macroremains indicate that both olives and grapes were transported to the site in Late Antiquity, although the press was not in use. Pollen evidence indicates that olives were grown about 1 km from the site at this time, and grapes less than 1 km away.|@mercuriCaseNuoveBotanical2020|
|Roma, Schola Praeconum|5th century CE|urban|The assemblage is scarce, only one grape seed can only attest the presence of this plant. Olive is not attested.|@whitehouseScholaPraeconumCoins1982|
|Volterra, Podere San Mario|5th-6th century CE|farmhouse|Large quantity of mineralised grape seeds found in small pits. Only modest presence of olive remains. The abundance of grape remains and cattle (also used as dung) indicate that the economy did not change drastically in Late Antiquity.|@mottaPaesaggiDiVolterra1997|

: Late Roman sites in central Italy that provided archaeobotanical macroremains. {#tbl-late-roman-centr-it-bot-sites}

If we base our interpretation on more investigated areas, we notice a contraction in the production of cash crops starting in the 3^rd^ century CE in southern Italy, and later, in the 6^th^ century CE in the north. However, more observations or strong prior information are required to generate models with credible intervals that allow further discussions on these topic. At the present state, this research is not able to make robust associations between these trends and historical events, due to the qualitative nature of this discussion and the limitations in the dataset.

To address this issue, we could comment on previous historical work on the topic. Using settlement and ceramic data, some scholars pre-date the decline to the infamous "third-century crisis" (see @sec-lit-rev). At this time, the number of settlements was in decline, including villas. The contraction of settlements was also accompanied by a decline in the production of Italian wine amphorae, with some workshops abandoned in the early 2^nd^ century [@arthurProduzioneCeramicaAgro1987]. The villa-system crisis has been linked to the greater specialisation of other areas of the Empire in the production of cash crops, which were also imported to Italy [cf. @tcherniaRomansTrade2016, 312]. In this regard, Marzano [-@marzanoRomanVillasCentral2007,199] states:

> The idea that imports of wine and oil from Spain and Gaul put Italian slave-labor estates in difficulties, forcing a move towards tenancy and extensive cereal agriculture goes back to Rostovtzeff.

Although dated, Rostovtzeff's hypothesis is not to be entirely dismissed. A recent study [@jeromeAgriculturalDynamicsSouthwestern2023] conducted on 30 sites in south-western France, bordering Spain, indicates that vine cultivation was still flourishing in this region between the 3^rd^ and 5^th^ centuries CE. It is certainly not feasible to discuss market competition dynamics using palaeobotanical information alone, but what is interesting in @jeromeAgriculturalDynamicsSouthwestern2023's study is that the concentration of grape remains during this transition period is noticeably higher in rural sites rather than villas. This situation is entirely analogous to what our models' results show for Italy.

Therefore, whether external competition had an impact on Italian wine production in this period, its impact might have not been uniform across Italy, as we have observed earlier. Ceramic evidence also suggests that this crisis did not affect all winemakers:

> \[...\] competition from wine from Gaul would have harmed northern Campania and ruined the wine-growers in central Etruria, while sparing those in northern Etruria. Lastly, when the crisis in Italy is believed to have been at its worst, the end of the second century, there is even clearer evidence of another crisis in Gallia Narbonensis [@tcherniaRomansTrade2016, 313].

The transformations occurring in the Italian countryside after the 3^rd^ century had an effect not only on the prominent growers who exported wine to the provinces, but also on the smaller rural communities. Our results demonstrate that rural settlements were increasingly engaged in cultivating lucrative crops, including a rise in olive oil production, while such activity decreased significantly in the villas. However, the rural settlements' network likely stretched fewer distances than the villa-produced wine and oil did in previous times. We also have to consider that the decrease in the number of wine and oil amphorae finds during this period is possibly due to the transport of these goods in perishable containers [@panellaProduitsAgricolesTransportes1994, 159].

In certain areas of the peninsula, this contraction and change in productions must have instead been a deliberate choice. [@tcherniaRomansTrade2016; -@tcherniaRomansTrade2016, 305] reports that in the southern regions of *Apulia* and *Calabria*, for instance, olive groves were starting to disappear already in 50-30 BCE, as evidence from amphoras show. Our results, based on archaeobotanical evidence, also indicate a slow and general decrease in the south, which is not linked to any particular type of settlement. The reasons for this decrease are yet not entirely clear. Manacorda [-@manacordaProduzioneAgricolaProduzione1994; -@manacordaSullaProprietaTerra1995] suggests that in Calabria the fall was caused by the shift of the region's attention towards livestock breeding during Roman times. In contrast, @tcherniaRomansTrade2016 argues that market competition was the reason behind it. In the absence of zooarchaeological data from Calabria in this period, it is only possible to comment on other southern regions, which seem to have an agropastoral focus in the Roman phase. If this also applies to Calabria, Manacorda's interpretation seems reasonable. Whether this was also the result of a strong foreign market competition cannot be discussed with our data, as we would require samples from earlier periods.

This debate also serves as a useful starting point for commenting on some of the regional trends that emerged from our study on the presence of olives. In southern Italy, our analysis confirms an overall negative trend in olive cultivation during the first millennium CE. Even during the 11^th^ century, which is often associated with widespread agricultural revival, there does not appear to be a resurgence of olive growing. The revitalisation of olive cultivation in southern Italy must have been happened after, with a stronger establishment under Norman rule in the 12^th^ century CE [@piniViteOlivoNell1990, 346-7; @martinTravailAgricoleRythmes1987, 122-125; @cortonesiOlivasPreciosissimasVicende2018, 24-25; @caracutaOliveGrowingPuglia2020].

[@piniViteOlivoNell1990; -@piniViteOlivoNell1990, 338-9] reported the strongest decline in Italian olive farming and viticulture during the 6^th^ and 7^th^ centuries, implying that these crops were sustained either through wild variants or by cultivating them within the city limits, even in areas of cities that had been abandoned. As for olive farming, it is not possible here to deal with the varieties present in the botanical samples of this period at the subspecies level, but one can rightly consider this interpretation too drastic. In fact, the models and ubiquity scores never reported complete disappearance of olive pits in any of the Italian sub-regions. On the contrary, some regions specialised in olive growing. Already in the early medieval phase, sources report that the Lake Garda region in particular was well-known for its olive oil, and the establishment of olive groves was encouraged by monastic foundations like Santa Giulia di Brescia and San Colombano di Bobbio. The area around Lake Garda is particularly suitable for olive growing because the lake creates a microclimate similar to that of the southern Mediterranean, with moderate temperatures [@varaniniOlivicolturaOlioGardesano2005]. It is also plausible that olive cultivation was necessary for Christian liturgies, since olive oil, like wine, was used in religious ceremonies. Although our database contains archaeobotanical data from five sites in the immediate vicinity of the lake shore, none of them reported olive pits, so we cannot provide evidence for the specialisation of this region.

In line with the scenario suggested for olive production, the alleged late antique decrease in wine production proved less catastrophic than expected, with the exception of southern Italy where the shift towards cereal farming had already commenced in the 3^rd^ century. In general, a contraction most likely occurred within the large-scale farming operations typically associated with these crops. The analyses in this research demonstrates that the number of vineyards declined, and those that survived had to diversify their farming strategies to cater to different markets. While we cannot comment on yields, after the 3^rd^ century CE, the presence of grape remains consistently remained high (means above 0.40) in all regions and context type, excluding religious sites (where the model provided high density intervals that were too large to be trusted).

Remains of olives and grapes were not exclusively present on large rural estates but were also prevalent in urban settings, as evidenced by their significant presence in various archaeological contexts indicative of consumption. For instance, the marked presence of these botanical remains is evident in urban sewers, as demonstrated in *Herculaneum* [@rowanBioarchaeologicalPreservationNonelite2017], in waste pits in Cremona [@castiglioniMaterialiBotanici2018], and within residential complexes in *Pompeii* (Domus VI, 1 -- IX, 8) [@carraNuoviDatiArcheobotanici2017; @murphyArchaeobotanicalRemains2018]. Moreover, the presence of these crops is consistently high across both large rural estates and smaller farmhouses. The attempt to apply a purely quantitative analysis to these crops, akin to the methodology used for cereals, proved problematic due to the prevalence of outliers in the data, particularly concerning grapes and olives. This constraint hindered a comprehensive evaluation of the distinct contributions made by each crop towards the overall production of a particular site, which could have been informative. Nevertheless, it is plausible to suggest that smaller farmhouses also participated in the cultivation of cash crops already before the aforementioned supposed crisis, focusing on intensive, specialised production suitable for local markets rather than extensive farming aimed at large-scale exports. In this context, the perspective of Jean-Pierre Vallat [-@vallatSurveyArchaeologyRural1991,14] is noteworthy; he posits that:

> A slave villa such as Settefinestre might concentrate on oil, wine and polyculture, while small farms might prefer specialized production of valuable oil or wine or other market crops such as poultry, fish, or fruit.

Specialisation does not necessarily lead to monoculture, as seen in the varied range of cereals and legumes present in rural areas, hinting at the implementation of ley farming practices. Typically, Roman villas display a narrower variety of cereal types compared to smaller rural sites, which embrace a broader diversity as a risk mitigation strategy.

The differences in farming practices are more pronounced in the later phase as far as olive growing is concerned. While the presence of olive remains is stable (if not slightly increasing) in smaller farms, it decreases in larger agricultural operations. Although most of the sites in our database are located in the north, there is no strong imbalance in the location of settlements between Roman and late Roman assemblages, which may provide grounds to think that variations in the data may reflect actual agricultural changes.

These variations are interesting reflecting back on what we have seen for cereal farming. In the transition to late antiquity, the number of 'minor' cereals increases in central-northern urban and rural sites, and then explodes in the early medieval period in both types of sites. In large private agricultural estates, on the other hand, cereal cultivation certainly also increases (at the expense of cash crops), but mainly for naked grains and barley. All other crops -- at least those under examination -- slowly decline in villas in the later phases, while increasing in other rural and urban sites.

We can notice in our models a gradual increase in grape cultivation in rural areas from the 11^th^ century onwards. Nogara-Mulino di Sotto, a medieval village on the Tartaro River, just a few kilometres north of the Po River, shows a widespread cultivation of grapes during the 10^th^ century. This is also indicated by the presence of grape pollen, which is typically not dispersed far from its source [@marchesiniPaesaggioVegetaleAntropico2011, 173]. Between the 9^th^ and 11^th^ centuries, macroremains in Nogara were found to consist mainly of *Vitis vinifera* [@castiglioniNogaraAbitatoDi2011]. Historical records document intensified aristocratic investment in suburban rural areas of northern Italy during this time, where fields were transformed into vineyards to meet the demand of the expanding urban population. However, despite the limited number of assemblages from this period, the quantitative proportions present a different perspective, with only a handful of sites where the grape pips dominate the assemblage. It is only later that vineyards gradually replace other crops and become the dominant characteristic of rural landscapes; during the late Norman era in southern Italy and the second half of the 14^th^ century in the Po Valley [@cortonesiColtivazioneViteNel2003, 6-7]. Since the dataset limits the upper boundary to the 11^th^ century, there are no samples from this period to support this conclusion.

### Other fruits and nuts

The research aimed to contribute to the study of agricultural practices in the first millennium CE by focusing on the most economically significant plants and animals. Concentrating on species of secondary economic importance falls outside the scope of the project. Nevertheless, it is immediately evident that the diversity of species cultivated or used in this period is vast: the heatmap in @fig-heatmap-ubiquity-for-PDF shows a great diversity of fruits and nuts consumed in the first millennium. There have been several studies so far focusing on the introduction of species into the Italian peninsula, especially in the Neolithic period but also beyond.

Recently, @bosiNewCrops1st2023 explored the introduction of new crops in northern Italy during the first millennium CE. They note that most of the new introductions dated to this period are related to fruits. During the data collection phase, we came across many fruit types in the publications, some of which were not included in the dataset because they are rather rare and infrequent. This was also one of the main problems in modelling fruit species. The use of binomial models is not the most appropriate choice, as they would severely under-represent rarer species, which may instead be rarer for preservation reasons. Dedicated studies are therefore needed to overcome this problem with more appropriate distributions that can handle zero-inflated counts.

Despite being outside the primary scope of this research, fruits are worth discussing as they were clearly abundant (as evidenced by the model results) in each period. In particular, in the Roman period the results showed a high diversity of fruits in urban sites, reflecting wider access to markets. This diversity decreased in the late Roman period, only to increase again in the 11^th^ century. Conversely, rural sites increased their cultivation of different types of fruit after the end of the Roman period, indicating an increased importance of this resource in peasant diets.

Among the fruits consumed during this period, figs, peaches, and nuts deserve special mention. One of the emblematic fruits of the Roman period is the fig. The fig is an integral part of the Mediterranean botanical heritage [@zoharyBeginningsFruitGrowing1975]. Commonly cultivated alongside vines and olive trees [@zoharyDomesticationPlantsOld2012], its importance in the diet of the first millennium is illustrated by palaeobotanical evidence, particularly from the 1^st^ century BCE to the 3rd century CE, and again from the 10^th^ century CE onwards. Figs are frequently discovered in substantial amounts within archaeological samples and may overshadow the presence of other seeds. On occasion, they are also found alongside other small seeds such as grapes. This is commonly attributed to their typical consumption as whole fruits, leading to seed mineralisation and preservation within latrines [@bosiSeedsFruitsPollen2011]. The consumption and disposal of figs across multiple settlements are widely evidenced by numerous archaeological findings recorded in our database. The following examples represent just a small selection of the data available:

-   Domus of Triclinium, Pompeii (Insula VI, 1, 1), which yielded a remarkable amount of 15,101 fig achenes from a toilet feature [@murphyRomansRubbishRefuse2015].

-   Herculaneum, with more than 1,000 fig achenes recovered from the cardo V sewer [@rowanBioarchaeologicalPreservationNonelite2017].

-   Piazza Marconi, Cremona, with 2,608 achenes recovered from a wastepit [@castiglioniMaterialiBotanici2018].

-   Modena, Cassa di Risparmio, with 8,692 achenes recovered from a wastepit [@bosiLifeRomanColony2017].

-   Cascina S. Martino, Trezzo sull'Adda, with 499 achenes found in a wastepit [@castiglioniRestiBotaniciDalla2012].

Another fruit that appeared on Roman markets and rapidly gained popularity is peach. The introduction of this fruit (*Prunus persica*) in Roman times has already been studied by @sadoriIntroductionDiffusionPeach2009, who report its introduction from the 1^st^ century CE. We could probably anticipate this date to the 1^st^ century BCE, given more recent excavations that report the presence of peaches in Pompeii: the so-called Soap Factory (Insula VI, 1, 14) is the only context in the dataset where the peach is present before the 1^st^ century CE [@murphyRomanFoodRefuse2013; @murphyRomansRubbishRefuse2015]. Pliny referred to the fruit as costly [@jashemskiNaturalHistoryPompeii2002], and we find depictions in the frescoes of elegant villas in the Vesuvian region, as the cryptoporticus of the Domus of the Stags in Herculaneum (Insula IV, 21) [@croisilleNaturesMortesDans2015]. Our results show that the ubiquity of peaches decreased from the 4^th^ century onwards. Nevertheless, this figure increased again in the peninsula towards the end of the early Middle Ages.

In addition to figs and peaches, a range of fruits were present on the tables of Italy during the 1^st^ millennium CE, including domestic and wild varieties such as plums, pears, apples, various types of berries and even exotic fruits like dates. Excluding religious and funerary sites, which typically contain fruits and pulses such as dates, grapes, olives, pomegranates, nuts, lentils, and chickpeas [@robinsonDomesticBurntOfferings2002; @rottoliPlantOfferingsRoman2011; @caracutaPlantRitualsFuel2017], our models clearly indicate that the highest fruit variety in the Roman period could be found in urban sites and rural villas. It is interesting -- as already noted -- that these sites exhibit an immediate decline during the late Roman period, whereas there is a gradual rise up to the 11^th^ century in rural sites.

Despite their gradual decrease, fruits remained a crucial constituent of the early medieval city, holding a significant role in the diet. Their proportions as usually lower in publications than those of cereals, as fruits are commonly consumed in a relative short time rather than stocked, and as a consequence we rarely find large charred assemblages. In @sec-lit-rev, we discussed the topic of urban gardens, highlighting the common practice of cultivating different plant species within city walls during the late antique and early medieval period. The findings from this study seem to corroborate this assumption, with the increasing richness in urban contexts of edible plant species. In particular, this increase seems to be more related to cereals and pulses rather than fruits, probably as a way of dealing with the uncertainty of the times and to save on taxes [@andreolliRuoloOrticulturaFrutticultura1990, 183]. In the kitchen garden at Brescia (Ortaglia) from the 6^th^ to the 7^th^ centuries, archaeobotanical remains indicate the cultivation of at least eight varieties of cereals and four types of pulses; the remains of fruits were rare, with only one walnut, grape, and peach remain [@castiglioniBrescianArchaeobotanicalStudies2019]. It is reasonable to assume that an urban kitchen garden would include fruit trees interspersed with cereal and legume crops grown in their proximity. @goodsonCultivatingCityEarly2021 examined textual sources to investigate this phenomenon in various Italian cities, such as Rome, Naples, Milan, Lucca, Ravenna, Bari, and others. This analysis is valuable because many of these major cities lack archaeobotanical analyses, a situation aggravated by the challenges in deposition and preservation (see @sec-materials-bot).

In some cases, textual sources point to the special care of urban gardens. The 'dark earths', i.e. the accumulation of organic material in cities, a phenomenon typical of the early Middle Ages and particularly evident in the 5^th^ and 6^th^ centuries, have often been interpreted as indications of urban decline and ruralisation. Some archaeologists propose however that they may alternatively be part of a methodical and centralised system that integrated the requirement for urban waste disposal with the agricultural undertakings that occurred within multiple urban areas [@laroccaDarkAgesVerona1986; @arthurNaplesCaseUrban1991; @goodsonCultivatingCityEarly2021, 73-4]. In the early medieval period, cultivating the city became a necessity:

> Given the absence of commercial-scale farming of fresh food, apart from grain and some olives and wine grapes, household- level cultivation was, for the period between about 500 and 1050, the principal means of acquiring fresh food for most city-dwellers [@goodsonCultivatingCityEarly2021, 235].

We must also consider that agriculture was not the only way of acquiring food resources. At this stage it is hard to provide robust interpretations, but we believe that the increased presence of wild fruits (i.e. berries and other undomesticated fruits) in late Roman and early medieval urban botanical assemblages does not depend on sampling bias, but it is rather a sign of an increased need on the part of city dwellers to make use of all the resources at their disposal.

In addition to the fruits mentioned so far, another significant category of produce were nuts. The dataset reports counts of hazelnuts (*Corylus avellana*), walnuts (*Juglans regia*), and chestnuts (*Castanea sativa*). These nutritious and storable taxa were fairly common among classical and post-classical assemblages, and could be either cultivated locally or transported in amphoras [@banducciMaterialEvidence2019, 40]. While hazelnuts are an indigenous plant that often grows as a shrub, walnuts and chestnuts are often used as indicators of human management of forests [@mercuriOleaJuglansCastanea2013]. Pollen evidence indicates that the cultivation of both *Juglans* and *Castanea* expanded in the Roman West [@krebsRomanLegacyEuropean2022; @pollegioniRethinkingHistoryCommon2017]. While Pliny seemed to favour the medicinal aspects of walnuts [@murphyRomansRubbishRefuse2015,99; @casas-agustenchMediterraneanNutsOrigins2011], the plant was likely used for food and was indeed considered a delicacy [@brothwellFoodAntiquitySurvey1998, 150]. Our results confirm that nuts were especially found as part of ritual offerings, but also in urban markets and in rural villas in the Roman period. Instead, in the post-classical phases they are mainly presents in fortified sites and then similarly present across other site types. Although our research does not involve anthracological remains, it is important to note that nut trees were also cultivated for their timber. Timber held significant economic value in the Roman world and later, as it was used for buildings, fuel, and other purposes [@harrisIndispensableCommodityNotes2017, 228; @harrisDefiningDetectingMediterranean2013; @meiggsTreesTimberAncient1983].


It is amply documented how during the early Middle Ages chestnuts gained popularity in the Italian landscape. The history of the introduction of sweet chestnuts in Italy is interesting and deserves a separate assessment. The fruit was certainly known to Romans, and it is found sporadically in archaeobotanical assemblages from this period. Examples in this database are the villa of Vada Sabatia (Liguria) in archaeological layers dated between the 1^st^ and 2^nd^ century, and the 2^nd^ and 3^rd^ century CE [@arobbaRomanLandscapeAgriculture2013], or the necropolis of Mariano Comense (Lombardy) in the stratigraphy from the 1^st^ century BCE to the 3^rd^ century CE [@rottoliPlantOfferingsRoman2011]. However, it seems that the intensification of the cultivation of this tree, planted in large forests, is most likely a post-Roman phenomenon [@conederaCultivationCastaneaSativa2004; @conederaDistributionEconomicPotential2004; @quiroscastilloCambiosTransformacionesPaisaje1998]. Squatriti [-@squatritiLandscapeChangeEarly2013; -@squatritiBarbarizingBelPaese2016] in particular has studied the spread of the chestnut in both northern and southern Italy, tracing the origins of the reinforcement of the close relationship between this tree and man since late antiquity. This relationship was still quite strong in the peninsula in the last century, as the chestnut made a substantial contribution to the diet of alpine and mountain communities [@ferrariAssaltoAlleAlpi2023,76,122; @bevilacquaEmigrazioneTransoceanicaMutamenti1981; @nanniCittaCampagnaNella2005; @casanovaVitaCacceContadini2007], and even today this fruit is particularly appreciated in the autumn months in Italy.

In @sec-lit-rev, we discussed how chestnuts became an integral part of the diet in the early Middle Ages. The fruits were often dried and ground to produce a flour that could be used to make bread, which was less nutritious than bread made from cereals, but still had some nutritional value. Although chestnuts are occasionally mentioned in agricultural contracts [@andreolliRuoloOrticulturaFrutticultura1990; @andreolliContrattiAgrariTrasformazione1989; @andreolliProdottiAlimentariNei1981], their increased use is a sign of a subsistence economy in which people exploited the land and resources close to them. The "Italians" of the early Middle Ages made great use of wooded areas. As we shall discuss shortly, in this period pigs were more likely to be reared in woods than in enclosures. For example, chestnut groves were introduced around the fortified village and castle of Miranduolo (Tuscany), where the tree was exploited for both wood and for its fruit in the 10^th^ century CE [@buonincontriTransitionChestnutCastanea2015; @buonincontriMultiproxyApproachStudy2017, 667]. Chestnuts are rarely preserved in archaeobotanical contexts, and consequently the species is underrepresented. Despite this bias, our results showed a marked increase in the presence of chestnuts in the 9^th^ century. This is consistent with the current historical understanding of a subsistence economy that relied to a great extent on forest resources.

## Animal husbandry

The most common faunal remains in the 1^st^ century CE assemblages are cattle, sheep/goats, and pigs, which are present in all the sites investigated. Occasionally, the assemblages also include other species such as domestic poultry and other birds, fish, game animals, and marine or terrestrial molluscs. Overall, the data models consistently indicate a marked preference for medium-sized animals throughout the millennium, with pigs emerging as the most prevalent domesticated species in all phases.

Of the four primary domesticated species, pigs are unique in that they were primarily used as a source of meat with no significant by-products or secondary functions during their lifetime. In contrast, cattle and sheep/goats were raised for multiple purposes beyond meat production. Cattle, in particular, were an integral part of pre-modern agricultural systems, primarily as draft animals, with some authors associating cattle husbandry with an economy predominantly focused on cereal production [@salvadoriTransitionLateAntiquity2019, 39]. For this reason, cattle were usually butchered at a later stage. In an initial survey of Roman sites in Italy, [@mackinnonProductionConsumptionAnimals2004; -@mackinnonProductionConsumptionAnimals2004, 79-80] reported that most cattle remains in both urban and rural contexts showed signs of slaughter after 3.5 years.

Apart from cattle, sheep and goats were also raised for the production of milk and wool. These animals were the primary source of milk in both classical antiquity and the medieval period, although milk consumption by adults was likely rare due to its association with infant nutrition. In turn, cheese was very popular in antiquity, as this was a convenient method of preserving milk [@montanariLatteSuoiDerivati2000; @pantaleonedaconfienzaFormaggiMedioevoSumma1990; @carusoMarziale1330332015; @mackinnonMeatOtherAnimal2019].

To comprehend why these four animal species were so prevalent, it is necessary to examine the archaeological contexts from which our data are derived. Much like the palaeobotanical assemblages previously discussed, the zooarchaeological data mostly refers to human activities (and waste) rather than natural deposition patterns. This focus unavoidably affects the reported abundance of certain species, as these contexts are more indicative of human consumption and activities rather than reflecting the actual populations of animals in the wild.

In @sec-lit-rev we have stated that the data available for the peninsula are limited both geographically and temporally. Spatially, we can see a preferential distribution of sites along the Thyrrenian coast and parts of northern Italy. In particular, there are large concentrations of assemblages in the Rome-Ostia area. The chronological distribution of the sites is more even, with the late Roman phase being the most represented and the 11^th^ century phase being the least represented.

No comprehensive databases containing data from this region and time period were available when this research began. This section will compare our findings with those of previous publications [@salvadoriUominiAnimaliNel2015a; @salvadoriZooarcheologiaControlloRisorse2011; @salvadoriTransitionLateAntiquity2019; @rottoliReflectionsEarlyMedieval2014; @degrossimazzorinAnimaliRomaTre2022; @schmidtovaPresentingRomAniDatData2023], in order to analyse and interpret the identified trends.

### Pigs

In accordance with the findings from the RomAniDat dataset [@schmidtovaPresentingRomAniDatData2023], our analysis reveals a notable predominance of pig remains during the first centuries of our investigation, with an increase continuing until the 2nd century CE. This trend is observed predominantly in southern-central Italy, especially in coastal and plain areas, while higher altitudes showed a predominance of sheep, goats, and cattle. This rise in pig remains likely reflects the growing demands of urban markets, corresponding with the demographic peak of the Roman age during the 1^st^ and 2^nd^ centuries CE [@frierDemography2000; @hanson2016]. The demographic growth's impact was particularly pronounced in Rome, as already highlighted by De Grossi Mazzorin and Minniti [-@degrossimazzorinAnimaliRomaTre2022, 38], who observed a peak in the proportion of pig remains during the Imperial age.

This phenomenon begs the question - why is an increase in the number of pigs associated with the demographic situation? Pigs are one of the most practical choices for protein production. Although cattle are the most productive animals on a farm in terms of meat yield, they can only produce one calf every nine months. Sows, on the other hand, can produce eight or more piglets in about four months [@harrisGoodEatRiddles1998, 67]. Taking this into account, De Grossi Mazzorin and Minniti [-@degrossimazzorinAnimaliRomaTre2022, 39] have calculated (using modern zootechnic standards) that a cow can produce an average of 15.5 kg of meat in one month, while a sow can produce about 160 kg.

To substantiate the association between pigs and demography, and further understand the capital's influence on this urban trend in pig consumption, we modelled separately data from urban sites and from Rome and Ostia specifically. The results were informative, showing a substantial impact of the capital's assemblages on overall urban estimates, with a greater than 0.20 point difference in pig remains in the Roman period, narrowing in later periods. In contrast, the same differences are negative in the sheep/goats and cattle models, suggesting that these animals were more commonly found in smaller settlements rather than Rome. Within Rome, the assemblages from the Flavium Amphitheatre are particularly striking, as the waste here mainly consisted of pig remains.

The consumption of pork was also high among the villas, mirroring the urban trend. Within these properties, it is probable that pigs were bred on-site rather than being imported. In the late Republican and early Imperial period, it was indeed desirable for villas to maintain their original functions of agricultural production, while other displays of wealth that were deemed unproductive were disapproved of by writers such as Varro [@marzanoRomanVillaOverview2018, 10]. As they cultivated profitable crops, Roman villas also dedicated significant attention to livestock raising. MacKinnon [-@mackinnonHighHogLinking2001, 665] already highlighted that the most concrete archaeological evidence for a pigsty from the Roman period in Italy is found at the renowned villa of Settefinestre. This site is particularly significant due to the discovery of a structure with 27 rooms identified as a sty, demonstrating a sophisticated level of organised animal husbandry [@ricciPorcile1985]. To our knowledge, this is still the only safe identification. In the words of MacKinnon [-@mackinnonHighHogLinking2001, 665]:

> "One problem is that the function of many rooms cannot always be determined on the basis of available archaeological and architectural evidence. Often the designation of 'stable', 'pen', 'sty', and so forth is based chiefly on the position and dimensions of the room or structure in relation to other rooms, and not on zooarchaeological, botanical, entomological, or other biological, chemical, or geomorphological evidence that might help indicate the room's inhabitants".

At the start of the late Roman period, there appears to have been a decline in pig farming. This research showed how the drop was particularly evident in urban sites, whereas rural sites only experienced a slight decline. Along with other urban sites, pork consumption decreased also in Rome. Biometric studies examining pig remains in the capital indicate that their sizes increased during this period, potentially due to pigs being reared locally in an open environment (i.e. forests) rather than imported, resulting in a larger size [@degrossimazzorinAllevamentoApprovvigionamentoAlimentare2001; @degrossimazzorinSfruttamentoAnimaliDomestici2016; @minnitiMeatConsumptionIdentity2016; @albarellaUrbanPigsDietary2019; @minnitiBiometricVariationDomestic2022].

In contrast to this trend, rural villas showed an increase in production. A notable example is the villa of San Giovanni di Ruoti (Basilicata), which was constructed in the early imperial period but abandoned in the 3^rd^ century CE. During the 5^th^ century, the villa underwent a significant expansion and renovation, exhibiting characteristics common to the late antique villa revival trend including an apsidal hall, a large dining room and other luxurious rooms [@smallVillaRomanaTardoantica2016]. This revival was particularly evident in regions such as northern Apulia, Lucania, Sannio, and Sicily (cf. @sec-lit-rev). In San Giovanni, a substantial quantity of pig remains were discovered in the zooarchaeological assemblage dating from the 5^th^ to 6^th^ century. Here, the culling of the herd was carried out in an organised and planned manner, as indicated by the kill-off patterns [@mackinnonExcavationsSanGiovanni2002]. This breeding strategy is consistent with the hypothesis [@barnishPigsPlebeiansPotentes1987, 159; @steeleAnalysisAnimalRemains1983] that the villa may have been involved in the late antique pork supply chain, serving urban centres and Rome. In fifth-century Rome, the requirements of the pork dole, which is thought to have been first introduced into the state distribution system by the Emperor Aurelian [@erdkampFoodSupplyCapital2013, 267], were considerable, requiring the provision of around 25,000 pigs from the southern regions in 419 CE, rising to over 30,000 by 452 CE [@barnishPigsPlebeiansPotentes1987,160-2].

The high demand for pork extended beyond urban centres. The establishment of a new network of *castra* in the Alps suggests a substantial requirement for pig meat, in addition to sheep and goats, which already had a longstanding presence in the Alpine region [@riedelArchaeozoologicalInvestigactionsNortheastern1994; @tecchiatiDinamicheInsediativeGestione2010; @riedelSettlementsEconomyBronze2001]. This increased demand was likely driven by the provisioning needs of the military garrisons stationed there. For instance, archaeological findings at the *castrum* of Monte Barro in Lombardy reveal that 49% of the faunal remains from the 5^th^-6^th^ century were pig bones [@bakerFauna1991]. The greater concentration of pig, poultry and fish remains in the palace area than in the rest of the settlement reinforces the idea of an elite consumption of these resources [@chavarriaarnauUominiAnimaliNell2017, 164]. Similarly, excavations at the *castrum* of Loppio in Alto Adige/Sdtirol, dating to the same period, reported a composition of 34% pig remains and 29% sheep/goat remains [@marconiFaunaInsediamentoFortificato2010]. The trend becomes more evident in the later stages, especially as more sites are fortified. This is clear from the dataset, which shows a significant rise in the number of such elite settlements.

The culmination of this development is observed in the 10^th^-11^th^ centuries, coinciding with the peak of the *incastellamento* phenomenon. It is also worth adding that in the early Middle Ages, pork -- and meat in general -- evolved into a distinct symbol of social status. In a culture where the elite were closely associated with a military persona, the image of a warrior deriving strength from meat consumption held significant symbolic power in demonstrating wealth [@montanariMedievalTastesFood2015, 60]. The preferential consumption of pork was also prevalent in other fortified settlements throughout Europe, such as those in the Basque Country [@quiroscastilloEarlyHighMedieval2016, 322; @quiroscastilloArchaeologyEarlyMedieval2020; @lubrittoNewDietaryEvidence2017], southern France [@durandApprochesBioarcheologiquesHabitat1997], Belgium/Netherlands [@vanpouckePigHusbandryEnvironmental2007], and Poland [@jarczykPreferencesMeatConsumption2011]. An exception to this trend is early medieval Sicily, where pork does not seem to feature in the diet of *castra* sites, even during the Norman/Aragonese period. This could be attributed to the persistence of Islamised communities [@anicetiWhoEatingPork2022].

Historians have placed particular emphasis on the consumption of pork in their historical reconstruction of the diet and agricultural practices of the early Middle Ages in Italy. The swine explosion of this period was unprecedented--- pigs were in every cookbook, they appeared in laws, forests were measured by the number of pigs they could host, and the swineherd became one of the most respected Lombard serfs [@montanariAlimentazioneCulturaNel1988, 57-8]. Pig also became a Christian marker in this time, contrasting the Jewish and Muslim diet [@montanariMangiareCristianiDiete2015, 143-144].

Our findings provide a contrasting view to the commonly accepted historical narrative regarding pork consumption trends during the early Middle Ages. First, a macroscopic view of the data indicates a decrease in overall pig meat consumption compared to the Roman period. While there was a revival of pig meat consumption in the 8^th^ century, and the 9^th^ century's estimated mean approaches that of the Imperial period, the overall probability of pigs occurrence in the early medieval assemblages remains lower than those dated to the Roman age. Second, a distinct trend is observable when comparing rural and urban sites. During the early Middle Ages, rural sites record more frequent instances of pig remains than in the Roman period. Conversely, urban sites demonstrate a general decline in pork consumption until the 11^th^ century, which plausibly reflects demographic changes. Third, it is possible that the overarching historical and archaeological narrative has been shaped principally by northern Italian sources^[cf. @salvadoriZooarcheologiaControlloRisorse2011; @rottoliReflectionsEarlyMedieval2014]. This is evident in the macroregional trends: up until the 11^th^ century, the assemblages from central and southern Italy demonstrate clear negative trends in pig remains, in contrast to the north, which shows a marked increase.

The impact of Germanic culture on pig farming and consumption patterns in northern Italy was likely one of the relevant factors in this increase. Germanic societies - whose nourishment mainly consisted of meat - held certain myths revolving around pigs, for example, the "Great Pig" that soldiers cooked and ate daily, only to see it reborn the following day [@montanariMedievalTastesFood2015, 165-8]. Norse mythology describes Gullinbursti, a mythological boar associated with fertility, capable of outrunning any other animal and shining in the darkness [@sturlusonProseEdda1916, 145-6]. The division between humans and nature dissolved as forests ceased to hinder economic development and instead became beneficial resources: one innovation of the early Middle Ages was the practice of rearing pigs in woodland areas, where they could subsist on acorns from oak groves (*silva glandifera*) [@montanariMedievalTastesFood2015, 164; @wickhamLandPowerStudies1994, 184]. In the Alpine region, this fact is supported archaeologically via isotope analyses of pig bones originating from the Adige Valley [@paladinEarlyMedievalItalian2020]. In describing the spread of pigs in the early medieval West, Kreiner [-@kreinerLegionsPigsEarly2020, 78] makes a good point:

> "\[...\] it was possible to raise a pig almost anywhere, as long as an adequate supply of water was available. This made pigs a good investment, because in almost any ecology, the animals could reliably transform resources that humans would not otherwise use (acorns, grubs, household garbage; the list goes on) into energy they could use. By some calculations, over 80 percent of a pig's weight amounted to edible, meaty energy---so even the leaner, active pigs of Late Antiquity and the early Middle Ages could have produced approximately 100--175 pounds (or 50--80 kg) of pork and lard."

This less intensive approach to pig rearing likely indicates a form of non-specialised farming, where the meat produced was intended primarily for local consumption [@chavarriaSettlementLandUse2016, 136]. It must also be noted that pork could easily be stored for longer periods if kept in a cold and damp room, or in the snow [@andreAlimentationCuisineRome2009, 141].

Overall, the results suggest that pork was the most consumed source of meat protein during the first millennium. However, pig rearing varied during this period, ranging from intensive, specialised rearing for urban meat markets in the Roman period to less specialised and localised rearing strategies in the early medieval period. The historical literature has overestimated the increasing importance of pigs in the early medieval Italian diet: pork consumption did increase, but only in northern Italy.

### Cattle

In contrast to pigs, cattle show the lowest distribution among the four main domesticated species throughout the first millennium CE. While modelling the NISP counts does not consider that a single cow yields considerably more meat than pigs or sheep/goats, rearing cattle exclusively for meat production was not the most profitable farming option, as previously discussed. Indeed, Roman agricultural practices often prioritised the use of cattle for draft work and dairy production, rather than exclusively for meat. This approach is evident in historical texts: Columella, for example, highlighted the significance of rearing oxen for field labour, whilst Varro broadened the scope to encompass dairy operations [@ikeguchiBeefRomanItaly2017, 31]. Moreover, analysis of the kill-off patterns for Roman Italy indicates that cattle were predominantly slaughtered at an older age, a stage when the quality of the meat would not be at its prime [@mackinnonProductionConsumptionAnimals2004, 79-80]. The important role of cattle in Roman agriculture is underlined by zooarchaeological evidence suggesting a specialisation in cattle rearing. In particular, an increase in the height and width of these animals was observed, particularly between the Republican and Imperial periods [@mackinnonCattleBreedVariation2010; @degrossimazzorinAnimaliRomaTre2022]. Recent scholarly debates, however, have re-examined the extent and nature of this Roman specialisation. While the domestication of animals since prehistoric times is generally associated with a gradual reduction in size [@meadowOsteologicalEvidenceProcess1989], recent research suggests that the improvement of breeding strategies in Italy may have begun before the establishment of Roman dominance in the peninsula. This perspective is supported by the work of Trentacoste et al. [-@trentacostePreRomanImprovementsAgricultural2018; -@trentacosteNewTrajectoriesAccelerating2021], who analysed log standard index (LSI) values and mandibular third molars (M3s) from different sites in northern Italy. Their findings suggest a trend towards increasing bovine size from the Bronze Age to the Roman period, challenging the traditional understanding of the Roman influence on cattle breeding and domestication.

Cattle sizes seem to have differed across the peninsula. In a paper where he compared literary evidence with zooarchaeological data, @mackinnonCattleBreedVariation2010 tried to establish the presence of different varieties of cattle in Roman Italy. Overall, both textual and zooarchaeological evidence confirmed that northern Italian cattle was smaller in size than central and southern Italian 'breeds'. While this research cannot contribute to the debate on cattle sizes, it can discuss its abundance. Both @mackinnonProductionConsumptionAnimals2004 and @schmidtovaPresentingRomAniDatData2023 indicate that (despite the smaller size), cattle was indeed more abundant in the northern part of Italy. Our results confirm this trend, indicating much higher proportions than elsewhere. Our results confirm this trend, indicating significantly higher proportions in the north compared to other regions. Looking at the macroscopic trend, the model suggests a decline in cattle numbers during the Roman period until the 3^rd^ century CE, followed by a subsequent increase, which is more evident in rural sites. This increase, which is particularly marked in the north, reinforces the region's inclination towards livestock farming. The upward trend in northern Italy is particularly striking because it precedes a marked decline in the early medieval period, a pattern not observed in other Italian regions. During this phase, the overall presence of cattle appears to increase, peaking in the 6^th^-7^th^ centuries CE, especially in the central and southern regions. Valenti [-@valentiCampagneTrastormazioneAree2017, 141] has suggested that the most striking changes in landscape and settlement patterns during this period (particularly in the Lombard sphere of influence) can be seen in new forms of rural landscape, mainly based on fallow land and animal husbandry. Paleopathological analyses of human remains from established Lombard cemeteries dating from the 6^th^ and 7^th^ centuries also support the idea of a class of farmers and shepherds among the Lombard groups. In Collegno (Piedmont), Spilamberto (Emilia-Romagna) and Leno (Lombardy), in addition to elite burials, many skeletons show pathologies associated with intense labour [@valentiCampagneTrastormazioneAree2017, 141-2]. The peak in the 6^th^ and 7^th^ centuries contrasts with the results of a previous study by @salvadoriZooarcheologiaControlloRisorse2011, who dated a decline in both the population and size of cattle during this period. Instead, our results suggest that the most significant shifts in cattle husbandry occurred around the 8^th^ century CE, possibly linked to broader agrarian transformations. Cattle farming did not disappear from northern Italy. Interestingly, despite the decline in this area, our models suggest that the distribution of cattle in the early medieval period was relatively uniform across the peninsula. Furthermore, compared to the previous phase, there are no major changes in the distribution of cattle between different settlement types, suggesting a continuity in cattle management practices between urban and rural environments. Complicating the interpretation of these trends, the 8^th^ and 9^th^ centuries exhibit the highest variability within the dataset. While the estimated mean precision ($\phi$) for both centuries is acceptable, there is a notable spread in these estimates. This indicates considerable variability within the groups, suggesting that a larger sample size might be necessary for more precise conclusions. This dispersion in the assemblages these centuries is informative in itself. The lack of cohesion in the data could imply that farming strategies during these centuries were more localised and varied, rather than following a uniform, widespread pattern. This variation could reflect a shift towards more region-specific agricultural practices, possibly influenced by the differing socio-economic conditions across the peninsula.

The decline in the size and number of cattle during the post-classical period has elicited various explanations from scholars. Salvadori [-@salvadoriTransitionLateAntiquity2019, 39; -@salvadoriZooarcheologiaControlloRisorse2011] associates Roman and late Roman cattle farming almost exclusively with agricultural systems. As previously discussed, pigs were the preferred source of meat, with cattle being more closely linked with extensive grain production. According to Salvadori, a reduction in cattle numbers implied that the agrarian system was more based on smaller farming operations at this point. Other scholars, however, argue that the early medieval shift to pastoralism in some areas of the western Mediterranean involved using cattle and sheep/goats primarily for dairy production. In fact, although cattle was smaller in size, this would not have impacted its milk-producing capacity [@chavarriaarnauUominiAnimaliNell2017, 163-4; @chavarriaArchaeologicalResearchLate2021, 11]. A combination of these two hypotheses is plausible. Firstly, it is possible that early medieval mixed cereal and vegetable production focused on yield rather than quality, especially for smallholders, thereby requiring less labour-intensive cattle use. Secondly, promoting cheese production could have been a strategic move during times of uncertainty, providing a long-lasting and reliable source of protein.

Following this declining phase, cattle becomes more frequent in the zooarchaeological assemblages. Although the estimates for this period are more uncertain due to a smaller sample size, the general trend appears positive in 10^th^-11^th^ centuries. Also in this phase the context specific models do not reveal a significant effect size, with the most notable change being observed in religious sites. Despite this, it is clear that beef was not the preferred meat in monastic and religious contexts. The proportions of beef compared to pork are considerably lower in each site. For example, at the Farfa abbey, the 8^th^-9^th^ century assemblages predominantly contain pig remains (51%), followed by sheep/goats (32%), with cattle only comprising 10%. This pattern persists into a later phase (10^th^-12^th^ century), with similar distributions (64% pigs, 30% sheep/goats, 5% cattle). Additionally, we explored whether assemblages from Rome influenced the estimates for urban sites overall. It was found that cattle were more prevalent in smaller urban communities, which might have engaged in agricultural activities in their surrounding areas, compared to Rome. The increase in cattle remains in the 10^th^-11^th^ century contexts aligns with archaeobotanical data indicating a more widespread presence of cereals and legumes during this time.

The distribution of cattle remains is not only linked to socio-economic events: in any phase, the geographical context plays a crucial role. The elevation models show a definite correlation between cattle presence and altitude, suggesting that environmental factors significantly influenced livestock farming practices.

### Sheep and goats

Sheep and goats were the second most bred animal category during the 1^st^ millennium CE, according to zooarchaeological samples. In excavation reports, distinguishing between them is often complicated, hence why they are frequently listed as a single category due to the absence of crucial skeletal elements for identification. Rearing these animals has several benefits since they provide meat, milk, other dairy products, leather, and most importantly wool. In classical antiquity, the benefits of sheep farming for agriculture were well-recognised, with ancient writers extolling the virtues of natural sheep manure as a fertiliser [@galloPolisSfruttamentoTerra1999, 41]. In return for the array of benefits they provide, they require fresh fodder, which they typically obtain through grazing in pastures [@bonettoAgricolturaAllevamentoCisalpina2004].

The historical discourse on animal husbandry during and after the first millennium has often focused significantly on sheep and goats, particularly due to their association with transhumance. This phenomenon involves the seasonal migration of livestock from lower winter pastures to higher summer pastures, and it continues to be relevant in Italy today to a lesser extent. While our models, based on NISP data, may not directly contribute to this debate, they can serve as a valuable complementary source. Therefore, a significant portion of this section will be devoted to examining transhumance, with a particular focus on Apulia, where much of the scholarly discussion has been concentrated to date. Additionally, this section will interpret the broader trends in the occurrence of sheep and goats across the various contexts in our database.

Based on the chronological trends revealed by our models, clear patterns emerge in the distribution of caprine remains. From the 1^st^ century BCE, there is a marked decline, continuing until the 4^th^ century CE. This pattern is also observed by @schmidtovaPresentingRomAniDatData2023. At this point, a sharp reversal occurs, with an increase that persists until the 7^th^-8^th^ centuries. Subsequently, there appears to be a slower decline. These findings are in line with @salvadoriTransitionLateAntiquity2019, who also identified a turning point around the 9^th^ century and a subsequent increase in the 10^th^-12^th^ centuries. The latter is not evident from our samples, which extend up to the 11^th^ century. Like cattle, the 8^th^ and 9^th^ centuries are characterised by the broadest credible intervals for sheep and goats, partially due to a smaller number of zooarchaeological assemblages from this period and to a higher variability between samples.

While the trends we have observed offer a broad overview at the peninsular level, the picture complicates when we stratify the models by macroareas, revealing differing regional patterns. In southern Italy, the trends closely align with the overall peninsular estimates. Central Italy follows similar patterns at least until the end of the 10^th^ century. The most striking contrasts are to be found in northern Italy. Here, the data reveals a contrasting narrative showing decline in the population of sheep and goats over the course of the millennium with a subsequent increase around the year 1000.

When stratifying by context type, the most trustworthy trends (in terms of the credible intervals) are those for rural and urban sites. Sheep and goats remains appear to decline over time after the Roman period in rural farms, while they increase in the assemblages from urban settlements. Later, around the 11^th^ century, there appears to be a stabilisation in the curve in urban sites and an increase in rural sites. With this recall of our results in hand, let us now try to provide interpretations to these trends.

A large sector of the Roman economy was dedicated to textile manufacturing, with some areas in particular that were famous for the quality of their wool: Cisalpine Gaul (northern Italy), southern Gaul, and Apulia. Most ancient authors reference to large productions in cities as *Altinum, Parma, Mutina*, and the area around the river *Scultenna* (presently referred to as Scoltenna), with the *municipium* of *Patavium* (modern-day Padua) likely serving as a major coordinating centre for these activities [@moellerWoolTradeAncient1976; @vicariEconomiaCispadanaRomana1994; @vicariProduzioneCommercioTessuti2001; @cortiEconomiaLanaMutina2012; @cotticaDallaLanaAltinata2003]. Other authors, as Martial (*Ep.* 14.155), ranked the wool from Apulia as the one with the finest quality [@liuTradeTradersGuilds2013, 128-9]. Within Apulia, *Tarentum* (Taranto) and *Canusium* (Canosa) were renowned for their wool economies. Two imperial textile workshops (*gynecia*), in particular, were active during the Late Antique period in Canosa and the nearby city of Venosa (Basilicata) [@veraPaesaggiRuraliMeridione2005; @grelleLaneApuleTessuti2001; @volpeContadiniPastoriMercanti1996, 281-2].

Apulia's geographical advantage as the endpoint of a winter transhumance route also meant it had access to wool from spring shearing before the flocks moved to summer pastures [@flohrWoolEconomyRoman2016]. Post-shearing, the wool was processed and spun in specialised textile workshops. There is ample debate [@liuTradeTradersGuilds2013; @flohrConsumptionNotProduction2011; @flohrWoolEconomyRoman2016] about whether raw wool was processed locally or transported to larger workshops, such as those in *Pompeii* [@flohrTextileEconomyPompeii2013] or central Italy [@jongmanWoolTextileIndustry2000], for processing. This research does not delve into this debate, as our data does not contribute directly to it. However, our findings do reinforce the hypothesis of the presence of strong wool production centres both in the south and north of Roman Italy, and the spatial models in @schmidtovaPresentingRomAniDatData2023 seem to indicate clusters around the Po Valley and Apulia.

Sheep and goat rearing was undoubtedly a profitable activity, but our analyses suggest that it is unlikely that rural villa economies in the Roman period and beyond were specialised in sheep husbandry. Pigs were consistently the most important livestock on large estates. It is reasonable to assume that sheep and goats were kept for their manure, which was beneficial to the farms, or for their secondary products. In contrast, these animals were more common on smaller farms, which may have practised mixed farming already in Roman times, as suggested by botanical evidence. Roman farmers were aware that animal husbandry was one of the most lucrative aspects of the agricultural economy [@hollanderFarmersAgricultureRoman2019, 63-64; @kronRomanLeyfarming2000]. While smaller farmers may have engaged in convertible husbandry, the Roman elite likely directed their efforts towards the transhumant wool market. In the 2^nd^ century CE, even the emperor owned a flock of sheep at *Saepinum* [@corbierFiscusPatrimoniumSaepinum1983]. Later Roman administrations continued to support pastoral practices, although not as extensively as in the late Middle Ages, when this investment was at the expense of other agricultural sectors [@barkerArchaeologyItalianShepherd1989a, 13-14].

The existing literature on wool production and transhumance, particularly in southern regions like Apulia, indicates a crisis in the wool market between the 4^th^ and 6^th^ centuries CE. This crisis paralleled the decline of the imperial textile industry, which peaked in the 5^th^ century and was exacerbated by the broader administrative crisis of the empire [@grelleCanosaDauniaTardo1986; @giardinaUominiSpaziAperti1989, 98]. In fact, a significant portion of the imperial demand for wool had traditionally been driven by the army and the administrative machinery. During this period, while Apulian wheat production was highly regarded in literary sources, shepherds were often depicted as troublesome, almost bandit-like figures [@volpeSulleCondizioniEconomiche1992, 72-85; @volpeContadiniPastoriMercanti1996, 276-285].

The growth of cereal cultivation in the south in this period is supported by our botanical models, which show a particular focus on free-threshing wheats and barley. De Robertis [-@derobertisSulleCondizioniEconomiche1951, 47-48; -@derobertisProduzioneAgricolaItalia1972] initially argued that this shift towards cereal farming eventually led to the decline of the investments in animal husbandry, suggesting that competition for arable land disadvantaged sheep and goat rearing. However, this somewhat pessimistic view was later revised by other scholars who deemed a complete collapse of all pastoral activities, including private ones, as unlikely. Various historical documents and epigraphs suggest that sheep/goats farming continued into the 6^th^ century, supported by various documents and epigraphs [@veraResPecunariaeImperiali2002; @grelleCanosaDauniaTardo1986, 391-2; @grelleConclusioni2001, 654; @volpeSulleCondizioniEconomiche1992].

While our models suggest a decline in the number of sheep and goats in the north, southern models indicate an increase in caprine abundance. In many of the southern Italian assemblages from the early medieval period, sheep and goats are the most represented category. We must therefore agree with those who question the idea of a total collapse of pastoral activities, assuming that cereal and livestock farming could be coexisting industries [@pasquinucciMontagnaPianuraTransumanza2004, 170; @volpeContadiniPastoriMercanti1996, 285; @volpeEconomiaCommerciInfrastrutture2023]. What is more plausible, is that the transhumance system underwent a transformation between late antiquity and the early middle ages.

The data from several sites included in our database, and others historically associated with the great Roman transhumance routes, offer important insights for reconstructing past practices.

At the site of San Giusto in Apulia, part of a large imperial estate (*saltus Carminianensis*), evidence extends beyond zooarchaeological findings to demonstrate the site's pastoral vocation, persisting into the early Middle Ages. Skeletal studies suggest that the site was probably associated to pastoral activities and the use of uncultivated land during the 5^th^-7^th^ centuries. In fact, one of the skeletons exhibited signs of brucellosis, a disease contracted through the consumption of infected dairy products or through contact with animals [@sublimisaponettiPaleobiologiaDiCampione2005; @buglioneDalTavoliereAlle2015].

At the nearby former Roman villa of Faragola, which in the early medieval period was likely a Lombard *curtis*, faunal remains predominantly represent sheep and goat farming in the 6^th^ and 8^th^ centuries. This marked a change from the previous phase of occupation (4^th^-5^th^ centuries), when most of the animal remains found in the villa were of pigs [@buglioneAnimalManagementSupply2007; @buglioneRicercheArcheozoologichePuglia2006].

In the same period, wither height measurements from various contexts in northern Apulia, including San Giusto, Faragola, and *Herdonia*, suggest that caprine measurements increased (average wither height = 67 cm), and these were possibly part of extensive flocks, likely grazed in uncultivated areas [@volpeLanePecorePastori2012, 254].

The continuity of stable wool production is also supported by the faunal assemblage from the Byzantine phase of the villa in loc. Vassarella-Casino Vezzani di Crecchio, Abruzzo (6^th^-7^th^ century CE). Although very informative, being located on a transhumant route from Abruzzo to Apulia, this settlement was not included in our database due to the absence of raw data in the publication [@degrossimazzorinEconomiaPastoraleEd1993]. Along the same route, the 6^th^-9^th^ century assemblage from Santa Maria in Civit in the Biferno Valley, Molise, reported that over 50% of the total NISP were sheep and goat bones [@hodgesExcavationsD85Santa1980].

Towards the end of the early medieval period (8^th^-10^th^ century), bioarchaeological data from two contexts in Canosa (San Pietro and San Giovanni) continue to show markers of caprine breeding for wool production, even when sheep and goats appear to be in decline in other Italian contexts [@giulianiIndaginiArcheologicheNell2005; @buglioneRicercheArcheozoologichePuglia2006, 503-4; @volpeLanePecorePastori2012].

Transhumance in early medieval central Italy, particularly on the Tyrrhenian coast, has been somewhat overlooked in historical discussions. This practice, which involved winter grazing in areas such as southern Tuscany, the Pontine countryside and Viterbo, is documented in the early medieval period in references dating from the mid-8^th^ century (then again in the 9^th^, 11^th^-12^th^). These documents can be found in the records of the Abbey of Farfa (Fara in Sabina, Rieti), which highlight the seasonal migration of livestock through various areas, including the cities of Spoleto, Rieti and Ascoli [@pasquinucciMontagnaPianuraTransumanza2004]. This aspect is further developed by Pasquinucci [-@pasquinucciTransumanzaPaesaggio1990; -@pasquinucciFrequentlyWinterGrazing2021, 33] and Barker et al. [-@barkerInsediamentoAltomedievaleEd1988; -@barkerAncientModernPastoralism1991], with @barkerAncientModernPastoralism1991 providing an in-depth analysis of pastoralism in the Cicolano Mountains (Rieti). The latter work raises questions about the nature of these livestock movements, in particular their range - whether they were short or long distance migrations.
Zooarchaeological remains from the Farfa assemblage in the database confirm the importance of sheep and goats in the area, accounting for over a third of the assemblage [@clarkMonasticEconomiesAspects1997]. This pattern is consistent with evidence from other central Italian sites, although without reaching the higher proportions found in southern Italy during this period.

This brief assessment of archaeological and historical literature has pointed out to a decline in transhumance and pastoralism in southern Italy in the early medieval period. This decline has been linked to the collapse of the Apulian textile industry [@volpeAlcuniCenniSulla2010; @volpeApuliaTardoanticaVie2010] and, more generally, to the breakdown of the international wool market [@wickhamPastoralismUnderdevelopmentEarly1985, 432]. What happened then in the southern countryside, and how can we instead explain our reported increased abundance of these animals in the early medieval period?

Clementi [-@clementiTransumanzaNellAlto1984, 37-40] argued that the Greco-Gothic wars and the change of Lombard administration in the 6^th^ century interrupted the supply of sheep from Abruzzo to Apulia. According to Clementi [-@clementiTransumanzaNellAlto1984, 37]: "transhumance, it is obvious, requires political stability" and this practice must therefore have ceased in this period. It is however difficult to speak of a single form of transhumance in Italy, but rather of a plurality of 'transhumances' [cf. @marconeRapportoTraAgricoltura2016b]. In this respect, some authors have argued for a shorter-range transhumance in this period, rather than a complete cessation of pastoral practices. In particular, the early medieval transhumance would have taken the form of a vertical transhumance (*alpeggio*), from the mountains to the nearest valley, instead of the long-distance journeys typical of the Roman and late medieval periods [@volpeSulleCondizioniEconomiche1992,95; @volpeContadiniPastoriMercanti1996; @wickhamStudiSullaSocieta1982; @pasquinucciMontagnaPianuraTransumanza2004, 167].

Rather than thinking in dualistic terms about the debate between continuity and rupture, it would be more productive to rethink the very concept of transhumance and its forms. In addition to historical sources, our models are helpful in the assessment of the animal population trends. First, the modelled distribution of animal remains indicate that, after the Roman period, sheep and goats became gradually more common in southern Italian sites. These models do not describe the full life history of such mobile animals -- this would require isotopic studies -- but they do indicate where animals have been culled. Secondly, our altimetric models show interesting patterns in the distribution of caprine animals at different elevations. While in the Roman and late Roman periods sheep and goats are mostly killed at higher altitudes, later there seems to be an opposite trend.

In general, the transhumance practice concentrates lambing in the late autumn and winter so that the lambs can be slaughtered before the flocks move to higher summer pastures and the surplus meat can be distributed to markets [@volpeLanePecorePastori2012, 250]. Could the greater presence of sheep and goats in lowland areas at this time therefore indicate a reorganisation of production and transhumance practices?

If we agree with @clementiTransumanzaNellAlto1984, and Abruzzo indeed ceased to be the main supplier of sheep and goats to Apulia in the 6^th^ century, but wool production continued (albeit to a lesser extent), Apulia had to reorganise its stock raising activities in order to have access to raw material. We suggest then that the increased archaeological evidence for sheep and goats in the south is indicative of sedentary caprine farming and a consequent necessity for a -- more local -- reorganisation.

We cannot however estimate whether the actual number of sheep/goats passing through the region in the early medieval period was lower compared to the numbers guaranteed by the larger-scale Roman transhumance; for this estimation, we would need records which are not available. This supposition is however likely, since the demand for wool reduced after the political breakdown of the empire. What we *can* do with our models is provide scenarios for the reconstruction of the farming landscape, which saw an increased presence of sheep and goats alongside cereal fields. Sedentary caprine husbandry required the presence of uncultivated pastures, which are known from pollen data [@accorsiRicercheArcheoambientaliNella1995]. Moreover, if transhumance was practiced at this time -- in an landscape increasingly dedicated to cereals -- it must have been short-distance with herds moving to close by mountains or available fallow land (Pasquinucci 2004, 167).

A recent multi-isotopic analysis of faunal remains from an imperial site in the Basentello Valley, Vagnari (Puglia), indirectly provides further support to our hypothesis [@trentacosteIsotopicInsightsLivestock2023]. Situated near the Appian Way and adjacent to the historic transhumance routes between Lucania and the Murge, this site has long been associated with large-scale transhumance activities [@smallNewEvidenceTilestamps2003]. Instead, the new evidence from the estate suggests that the animals unearthed at the site were present throughout the year, with no discernible signs of seasonal migration to different ecological zones. These findings imply that if Vagnari was indeed involved in large-scale transhumance, these migratory flocks were kept separate from the local herd, which instead contributed to the agricultural activities and to the local demand for wool, dairy products and meat. Furthermore, the absence of long-distance transhumant sheep confirms that these were slaughtered at higher altitudes during the Roman period.

The Apulian herds increased in number after the Roman period, probably to fill the gap left by the cessation of long-distance transhumance. Much later, the phenomenon of transhumance in Apulia would grow and become increasingly structured, with the establishment in 1447 of the *Regia dogana della mena delle pecora di Puglia* by Alfonso I of Aragon [@licinioMasserieMedievaliMasserie1998]. In the late 17^th^ century, around five and a half million sheep were involved in the central-southern Apennines transhumance [@garnseyCitiesPeasantsFood1998, 199]. At the same time of the institution of the *Dogana*, the papal state also organised itself on the Aragonese model to regularise the transit of flocks in the 15^th^ century in central Italy [@mengarelliAgroRomanoSistema2010; @contiTransumanzaNelLazio1982].

The number of studies on sheep/goat farming in northern Italy is much more limited than for Abruzzo and northern Apulia. Our models clearly show a downward trend, at least until the 11^th^ century, probably linked to the rapid expansion of pig farming in the early Middle Ages. Whilst sheep and goats appear in agricultural documents and contracts from the Po area and Tuscany in the 7^th^ and 8^th^ centuries [@galettiAllevamentoOvinoNell1993, 50-2], they certainly played a marginal role in the economy compared to the large-scale wool production of Cisalpina in Roman times. The amount of uncultivated land available for pastoral activities in the north increased in this period [@varaniniAllevamentoTransumanzaLanificio2012, 305], but in the absence of other documents, and reflecting back on our palaeobotanical evidence, the agricultural economy here seems to be more related to a subsistence one. It is only in the 12^th^ and 13^th^ centuries that historical sources suggest a reorganisation of production in the wool sector, especially in Veneto [@varaniniAllevamentoTransumanzaLanificio2012].

### Other animals

In addition to the main four domesticates, excavation reports include a wider range of domesticated and consumed animals, such as birds, fish, horses, terrestrial and marine molluscs, and various wild fauna (venison, boar, hare, dormouse). These species are often rare or under-represented in archaeological finds, and thus require separately designed analyses.

Although our research focused on the main domesticated animals -- as they have a more substantial impact on the reconstruction of ancient husbandry practices -- in this section we offer overall chronological trends and interpretations for two categories of interest, namely domestic poultry and game animals. Despite the limits in our interpretations, it was important to build a comprehensive database that reflected the diversity of ancient Italian diets, while also providing a valuable resource for other scholars, enabling further research.

During the first millennium CE, domestic fowl, primarily chicken (*Gallus gallus*) and to a lesser extent goose (*Anser* sp.), were likely the fourth most commonly consumed meat source, according to our database. Our analysis of domestic fowl has solely concentrated on their chronological distribution in zooarchaeological assemblages. We did not build models that included other predictors (i.e. site type, macroregion, etc.) because of the risks related to subsetting datasets that contain rarer species. Moreover, birds and fish are subject to further bias, as they are severely under-represented in excavation reports. This is because smaller bones are harder to visually inspect and require targeted sampling methodologies (cf. @sec-materials-zoo).

Overall, the model indicates a rise in the abundance of poultry in Italy until the 4^th^ century CE. After this period, the consumption of domestic fowl became more popular and the animal was certainly no longer reared solely for ritual purposes. The curve stabilises until the 6^th^ century CE, and rises again during the early medieval period. However, the means are still below a 0.10 probability, meaning that poultry was a marginal contribution to the diet when compared to other meats as pork. Our observed increase in the Roman period is consistent with the findings of De Grossi Mazzorin and Minniti [-@degrossimazzorinAnimaliRomaTre2022, 76], who noted a rise in the diffusion of *Gallus* in the zooarchaeological assemblages from the city of Rome, which also coincided with an increase in chicken sizes.

Although a controversial topic, recent research on the domestication of chickens suggests that these birds were domesticated around the 6^th^ millennium CE in Southeast Asia, possibly in northern China [@edaReevaluationEarlyHolocene2016; @edaOriginDomesticChicken2021; @edaEarliestEvidenceDomestic2023]. The *Gallus* species was subsequently introduced to Europe, appearing in the Italian peninsula probably around the 6^th^-5^th^ centuries BCE. In Italy, chickens were associated with ritual practices [@corbinoEarliestEvidenceChicken2022; @greenBirdsRomanLife2023,60-72] and only in the Republican/Imperial periods the primary use of the species shifted to meat and egg [@degrossimazzorinIntroduzioneDiffusionePollame2000]. 

Contrasting with De Grossi Mazzorin and Minniti [-@degrossimazzorinAnimaliRomaTre2022, 83-4], who observed a decline in chicken consumption in early medieval Rome, our models do not indicate a similar trend for the rest of Italy. Instead, they reveal increased variability in the estimated abundances and in the precision of our models, suggesting a more heterogeneous pattern of fowl consumption during this period. Domestic fowl are well suited to urban environments or confined spaces due to their ability to live in smaller areas. They also provide a daily source of small amounts of protein, making them ideal for urban gardens. Despite the relatively low quantity of their bones found in archaeological assemblages, the postclassical increase in chicken consumption is evident in our model, and this interpretation aligns well with the early medieval need to secure food sources in close proximity to living areas.

Game animals also played a role in the diet, albeit a marginal one. Given the rarity of wild animal bones in the assemblages, the category 'edible wild animals' in our models includes more than one species, such as boar (*Sus scrofa ferus*), red deer (*Cervus elaphus*), fallow deer (*Dama dama*), roe deer (*Capreolus capreolus*), various lagomorphs (e.g., *Lepus* sp.), dormouse (*Glis glis*), and assorted wild birds (predominantly pheasants, ducks, etc.). Other wild animals including foxes (*Vulpes vulpes*), dogs (*Canis* sp.), bears (*Ursus arctos*), and others were included in the database, but were not modelled.

In this section, we will only provide a discussion concerning the role and prevalence of these wild species in the diet. @greenDidRomansHunt1996, examining Roman documentary sources, recognised that hunting was practised by various members of society for different reasons. Aristocrats would hunt as a sport, soldiers would undertake hunting activities as part of their military training, and people at the margins of society would hunt as a complementary source of food.

From our models, it is however evident how game was not the main source of meat, and in Roman Italy (and also later), subsistence strategies depended on the main domesticated species. These results also confirms previous studies on Roman hunting [@clarkMonasticEconomiesAspects1997; @clarkAnimalsAnimalProducts1989; @mackinnonSupplyingExoticAnimals2006]. In every period, the estimated means of wild animal remains consistently remain below a probability level of 0.05, with a slight increase observed from the 7^th^ to the 11^th^ century, particularly in central and northern Italy.

Our general assessment revealed -- although more data is required -- that there were no significant differences between urban and rural sites in any chronological period. However, the models predict higher estimates in elite contexts, such as villas and fortified sites. In the Roman period, curiously, religious sites seem to consume more game meat than other settlements, probably as ritual offerings. The association between hunting and elite contexts is also apparent in the hunting scenes depicted in the refined 4^th^ century CE mosaics of the Villa del Casale (Piazza Armerina, Sicily) [@paceMosaiciDiPiazza1955; @stegerPiazzaArmerinaVilla2017]. When large rural estates gradually lose their elite connotations, the presence of wild fauna declines.

According to historical reconstructions, the early medieval period saw a stronger link between the elite and game consumption. Hunting rights came to be increasingly restricted to the nobility from the 7^th^ century, and even more so around the 9^th^ and 10^th^ centuries [@wickhamLandPowerStudies1994,160-1]. In various areas of Italy, game was only reserved for the *venationes*--- hunting trips that defined the aristocratic warrior identity [@montanariPeasantsWarriorsPriests1999, 470-1; @montanariProductionStructuresFood1999, 452].

Despite the fact that we would expect higher game consumption at higher elevations -- because we would expect smaller plots and more woodland -- our models did not support this correlation. However, the study by @bakerPreliminaryAssessmentRole1994 is interesting in this respect. In her work, she examined the distribution of different body parts of wild animals in contexts located at different altitudes in northern Italy. Baker noted that larger species, such as venison, were hunted in the Alps and then brought down to the valleys (e.g. the Po Valley) for further processing, including leather and bone working. We cannot confirm this correlation, as we do not have body parts data, but this is an interesting hypothesis. We must also consider that the early medieval greater prevalence of woodlands in various parts of Italy, must have also facilitated hunting by creating more areas for wild animals to take refuge. The forest advancement is suggested by several sources [@accorsiArcheologiaPaesaggioIndagini1999; @cheyetteDisappearanceAncientLandscape2008,163-4; @christieConstantineCharlemagneArchaeology2006,487-491; @demajoWoodlandCivilisationEnvironmental2022, 53-5; @dipasqualeHumanderivedLandscapeChanges2014].

## Reconstructing Italian historical landscapes

Now that we have discussed each of the categories of plants and animals studied in this research, we will try and draw together these sources to provide a more macro-level interpretation. This section will present hypothetical scenarios of the agricultural economy in the four chronological phases relevant to this study.

### Roman phase (1^st^ century BCE -- 2^nd^ century CE)

In the Roman phase (1^st^ century BCE -- 2^nd^ century CE), we observed a relative homogeneity in farming practices across the Italian peninsula. The climatic stability of the Roman Warm Period (200 BCE - 200/400 CE ca.) likely contributed to the consistency in agricultural methods, with plants and animals generally adhering to their geographical requirements. Notable differences, on the other hand, are found primarily at the settlement level. Two predominant approaches to agriculture were identified: small-scale farming in minor rural settlements and export-oriented farming in large, high-status estates like rural villas.

In the smaller farms, intensive mixed farming was the mainstay. This approach involved cultivating several types of crops, a practice evident throughout Italy, coupled with the presence of livestock. This interpretation aligns with Kron's historical models [@kronRomanLeyfarming2000; @kronRomanLivestockFarming2004], which suggest that Roman farmers were aware of the benefits of convertible husbandry. Ley farming allowed for the efficient use of fallow land as pasture for sheep, goats, and cattle. In turn, these animals played a fundamental role in fertilising the land for subsequent sowing, thereby improving overall productivity. Archaeobotanical assemblages reveal a diversity of crops, implying that polyculture was a common practice in these smaller settlements. Although cereal production remained the backbone of agriculture, olives and grapes were also cultivated in rural sites at a lesser extent than villas. Among the cereals, free-threshing wheats, barley, and emmer were most prevalent, but other cereals were also cultivated. It is plausible, as suggested by Witcher [-@witcherAgriculturalProductionRoman2016, 467], that rural households cultivated different cereals for domestic use and market export. In addition to cereals, the cultivation of legumes was also observed, probably for both human consumption and animal feed. The coexistence of cereals and legumes in the assemblages further supports the hypothesis of a crop rotation system, in line with the concept of convertible husbandry.

In contrast to smaller rural settlements, rural villas, representing the larger estates, were inclined towards export-oriented farming and specialised in the production of cash crops such as olives and grapes. Villas also focused on a smaller number of cereals and other crops when compared to other rural settlements. While villas did cultivate cereals and other crops, their variety was typically narrower compared to other rural settlements. Outlining precise agricultural models for villas is challenging when relying solely on presence/absence archaeobotanical data. However, the crop selection in villas seems more compatible with extensive agricultural operations rather than intensive farming. Roman agricultural texts inform us that villas also raised animals, and zooarchaeological assemblages consistently show the presence of the four main domesticates. We can thus hypothesise that villas might have implemented rotation systems, allowing cattle and sheep/goats to graze in pastures. Furthermore, as previously discussed, the raising of caprine might have been a permanent feature of both villas and smaller sites. Recent analyses, such as those carried out in the imperial estates of the Basentello Valley [@trentacosteIsotopicInsightsLivestock2023], together with other historical debates [@kronArchaeozoologyProductivityRoman2002,54; @garnseyCitiesPeasantsFood1998], suggest that the modalities of transhumance in Roman Italy may still not be entirely clear.

The distribution and abundance of domesticates varied according to the specialisation of different regions in Italy. In the Po Valley, cattle were more commonly raised, while sheep and goats were prevalent in areas involved in wool production. Pig husbandry, however, emerged as a key component of the villa economy across the peninsula. In the north, as seen in Ronchi dei Legionari, Friuli Venezia-Giulia [@petrucciArcheozoologiaFriuliVenezia2008], and Isera, Trentino Alto-Adige [@riedelFaunaVillaDi2011], pigs and cattle were the principal species. In central Italy, sites like Mola di Monte Gelato [@kingMammalReptileAmphibian1997], Settefinestre, Tuscany [@kingRestiAnimaliMammiferi1985], and Ossaia, Tuscany [@bokonyiAnimalBonesOssaiaUnpublished], predominantly show evidence of pig farming. In the south, examples from Botromagno, Apulia [@small_roe_hayes_simpson_guzzetta_mackinnon_monckton_1994], and Masseria Ciccotti, Basilicata [@gualtieriVillaRomanaDi1994] indicate a mix of pigs, cattle, and sheep/goats, particularly in areas involved in wool production. The case of Settefinestre illustrates the significance of pig husbandry in the villa economy, where pig remains are abundant, contrasting with the lesser presence of cattle compared to other rural sites. This disparity further supports the correlation between cereal farming and smaller-scale farming operations.

### Late Roman period (3^rd^ -- 5^th^ century CE)

A significant change in agricultural strategies began to emerge around the 3rd/4th century CE, marked by geographical differentiation. Large-scale production underwent a reorganisation, with increased variability in cereal cultivation. In southern Italy, there was an increased focus on the cultivation of common Roman cereals such as free-threshing wheats, barley, and emmer. This trend suggests a growing importance of cereal production in these areas during late antiquity, aligning with the historical context discussed earlier. Our results seem to corroborate this emphasis on cereal cultivation in the south during this time. Interestingly, in these regions, there was also a noticeable decline in legume cultivation, further indicating a shift towards more extensive forms of agriculture. In contrast, central and northern Italy experienced an expansion in the cultivation of a broader range of cereal and legume crops. Alongside the main cereals, these regions started growing more rustic grains, with rye standing out in the north. Regional production differences were not only limited to cereal growing. Contrasting trends can also be seen in grape and olive production. In the south, the production of cash crops seems to contract from the 3^rd^ century in correspondence with the reconversion of production. In the north, on the other hand, production seems to intensify probably due to the contraction of foreign imports and the demands of the court that had moved to Ravenna in the 5^th^ century. The diversification in cultivation coincides with changing patterns in livestock farming. While the number of cattle, sheep and goats was on the rise in any region, there was a noticeable decrease of caprine in the north. In contrast, pig farming showed a decline in south-central Italy, potentially linked to demographic changes, while seeing a significant increase in the north. These contrasting trends in livestock farming across the peninsula suggest a move towards more localised farming and economic strategies, with extensive farming becoming more prevalent in the south and polyculture or intensive farming gaining prominence in the north and central regions.

### Early Middle Ages and the 11^th^ century

The late Roman changes are accentuated in the early medieval period, especially from the 7^th^/8^th^ century onwards, marking a significant turning point in crop choice and animal husbandry. Across Italy, the sites show an increased cultivation of cereals and legumes, irrespective of settlement type or location. Central and northern Italy, in particular, demonstrated a stronger reliance on more rustic cereals, a trend statistically supported by both a frequentist case study and Bayesian models. The decline of villas (especially in the north) and the emergence of fortified settlements as major storers of cereals and legumes highlight this shift. Free-threshing wheat and barley became more abundant cereals in archaeobotanical contexts, with a gradual decline in emmer. This cereal focus also explains the increase in cattle husbandry, which peaked in the 6^th^-7^th^ centuries but decreased later in the 7^th^/8^th^ centuries CE. The 7^th^ and 8^th^ centuries emerge as pivotal for studying agricultural economy, but the data available so far do not allow a more detailed study. In fact, the creation of models with a resolution of centuries would have produced credible intervals so wide that no convincing interpretation could be possible. The uncertainty in archaeological layer chronologies, mostly dated by ceramics, also contributes to this issue. Zooarchaeological studies can help to provide a more reliable date for the early medieval turning point, revealing evolving strategies in animal husbandry - cattle peaking in the 6^th^-7^th^ centuries, sheep and goats increasing until the 7^th^-8^th^ century and then decreasing, and a notable rise in pig numbers post the 7^th^ century, especially in northern Italy.

In summary, the early medieval period is characterised by two main trends: the first spanning the 5^th^ to 7^th^ centuries, and the second occurring during the 8^th^ and 9^th^ centuries. The initial trend, which emerged already around the 3^rd^ century, persisted until the late 6^th^ and possibly into the 7^th^ century. This trend is marked by an increasing localisation of agricultural activities. However, this shift does not signify a complete economic collapse. Rather, it suggests a strategic reorientation of the economy towards more self-sustained cereal cultivation and animal husbandry. This change could be viewed as a necessary economic reorganisation, particularly in response to the cessation of foreign grain imports during the late Roman period. The popularity of 'minor' cereals in the early Middle Ages, according to @montanariAlimentazioneContadinaNell1979, can be potentially also explained by their exemption from taxation^[Among the early medieval exemptions from taxation were urban domestic gardens. While @montanariAlimentazioneContadinaNell1979 stresses the importance of exemptions for the cultivation of rustic cereals, vegetables and fruit in cities, Goodson [-@goodsonCultivatingCityEarly2021, 21-22] has described several cases of urban gardens dating from before the 9^th^-10^th^ centuries, when exemptions are reported in northern Italian documents. According to Goodson, the gardens functioned as protective "cushions" for domestic consumption in times of need.]. The economy also becomes more pastoral, with sheep and goats grazing on fallow/uncultivated land. However, if transhumance was active, it was likely short-ranged, with an increase in sheep farming as a response to difficulties in moving large herds over long distances. This data suggests more continuity in the centre-south, while the north moved towards an economic and subsistence pattern reorganisation sooner.

In this framework, selections appeared to be following economic logic of cost and energy saving, which is also suggested by the development of urban gardens in cities. The shortage of workforce was further exacerbated by a demographic crisis. The population collapse cannot be related to changes in nutrition but was the result of multiple variables, particularly warfare and disease, the latter perhaps worsened by harsh winters [@barbiera2009]. The early medieval people were however able to adapt efficiently within these changes. Especially in the north, it is more evident how people were relying both on wild and domesticated resources for their diet (that was far from lacking variety), exploiting and taking advantage of their environment, and eventually domesticating forests with fruit trees (as chestnuts) where animals could graze.

While it is accepted that Germanic populations, including the Lombards, placed a high ideological value on animal husbandry and probably influenced local practices after their migrations (e.g. an increased emphasis on meat consumption among the elite), we must be cautious in making direct associations between specific diets and social or ethnic groups. As Wickham [-@wickhamPastoralismUnderdevelopmentEarly1985, 411-2] points out [commenting on @dubyGuerriersPaysansVIIeXIIe2021], the focus should be on geographical logic rather than ethnicity. As Italy became more forested and control over the landscape less pervasive, people adapted by exploiting the forests in similar ways: pig farming proved to be a practical and versatile choice in this context.

Previous historical debate has only partially explained the complexities behind changes in crop selection during this period (cf. @sec-lit-rev). One of the factors that may have played a role -- according to these reconstructions -- is the climatic instability of the 6^th^-7^th^ century (Late Antique Little Ice Age). Fluctuating temperatures and increased rainfall may have affected farmers' behaviour in relation to the crops they grow.

To fight climatic unpredictability, farmers could have used two methods: the selection of short-cycle crops with varied sowing and harvesting times, and utilising taxa that could be planted twice a year, such as millets.

In the event of a crop failure, these strategies mitigated the risks and allowed an alternative crop to be harvested in the summer. Millets, including proso and foxtail species, have been cultivated in Italy since the Bronze Age. Their rapid maturation (60-65 days after sowing) and potential for biennial cultivation, although sensitive to frost, make them a viable option in times of climatic uncertainty [@renfrewPalaeoethnobotanyPrehistoricFood1973, 99-100; @castiglioniBroomcornMilletFoxtail2013]. In addition, barley and rye, both of which tolerate cooler climates (but not extreme heat), were also potential options. Rye in particular is highly moisture tolerant and can grow faster than wheat at low temperatures [@renfrewPalaeoethnobotanyPrehistoricFood1973, 80-5; @leonardCerealCrops1963, 452]. The increased prevalence of these 'minor cereals' has consequently been often associated with the climatic anomalies of the period. However, if we were to support this conclusion, our results suggest that this correlation might only be applicable to northern Italy. Despite also experiencing climatic instability [@sadoriClimateEnvironmentSociety2016], southern Italy did not exhibit as much reliance on polyculture as the central-northern regions. The relationship between climate and crop selection is not entirely mechanistic. Therefore, we should avoid falling into the trap of environmental determinism when interpreting this. Furthermore, our models do not indicate any significant impact of changing climate on the cereals cultivated at lower altitudes. It appears that, across the peninsula, cereals respond similarly to altitude, and thus indirectly to temperature, in all phases of climate change. Although crop selection may have been influenced by climatic instability, a detailed understanding would require more extensive archaeobotanical data and precise climatic records. The obvious need is for greater temporal resolution, particularly in order to characterise the latter part of the early medieval phase with greater precision, a task that is not currently feasible. The 8^th^ century poses a specific challenge due to the scarcity of available sites from this period^[On this issue, see also @sec-conclusions.].

As more zooarchaeological data are generally available, the results of this study have been able to identify a final significant phase of change in animal husbandry during the first millennium, around the 9^th^/10^th^ centuries, which extended into the 11^th^ century. These findings indicate that the chronological divisions initially proposed in the methodology section (@sec-methods) may need revision in future studies. In this final chronological phase, several indicators point to economic growth. Firstly, the increase in pig populations in urban areas suggests a rising demand for meat, likely correlating with the demographic rise indicated by historical sources and paleodemographic studies [@locascio2005; @barbiera2009; @capassoEconomyPopulationItaly2012]. Secondly, the progressive growth in cattle numbers and the stabilisation of sheep and goat populations suggest that agriculture was reclaiming more spaces in this period.

Regarding the impact of climatic variations on cereal cultivation, it is important to approach this with caution. While the onset of the 'Medieval Warm Period' (c. 900 - 1300 CE) brought temperatures in the northern Hemisphere back to levels similar to those of the 'Roman Warm Period' suggesting a potential boost to agriculture, we must be wary of overemphasizing climate as a deterministic factor. The warmer climate may have created more favourable conditions for crop growth, contributing to agricultural recovery, yet this interpretation requires careful consideration beyond simplistic environmental determinism. The improved climate and reorganisation of territories likely contributed to increased security in plant selection. This period also coincided with the advent of castle building, which asserted new forms of direct control in the surrounding territory. Fields and domesticated trees began to replace wild forests as humans increased their control over the landscape. Documentary and archaeological sources report land clearance in northern and central Italy beginning in the early 9^th^ century [@wickhamLandPowerStudies1994, 195; @buonincontriShapingMediterraneanLandscapes2020]. During the Medieval Warm Period, free-threshing wheats are the most common and abundant cereals (perhaps mirroring a revival of the market system), followed by barley, rye, and proso millet. Interestingly, minor cereals were not completely abandoned. In tangent with the rise of temperatures, sorghum became more abundant in the 9^th^-11^th^ century. This rise likely stems from this taxon's ability to thrive in hot temperatures and tolerate drought.
