# Introduction {#sec-intro style="text-align:justify;"}

This research seeks to explore the dynamics of human-environment interaction in Italy during the first millennium CE. What plants and animals would you expect to find on a Roman farm? How did the agrarian practices differ in the Roman period between smaller and larger farms? When did the first moment of discontinuity in these practices occur? Were the Roman economic structures and farming practices completely abandoned or did they find continuity during the turbulent transition to the early medieval period? Which agricultural strategies did peasants develop to cope with political, demographic and climatic change?

Despite the increasing number of studies of plant and animal remains from archaeological excavations, a comprehensive synthesis of data on the Italian landscape during the 1^st^ millennium CE does not yet exist. Much of the existing literature focuses on specific, smaller areas or distinct chronologies within the peninsula, limiting the potential for broader comparative analysis across different regions. This study addresses this gap by providing the first coherent reconstruction of the Italian farming landscape of the 1^st^ millennium CE, based on legacy carpological and zooarchaeological data. By integrating various types of information, it becomes possible to reconstruct the complex interactions between humans and environment during this period.

This study focuses on 190 archaeobotanical assemblages and 466 zooarchaeological assemblages from a total of 309 sites, providing information for the period between the 1^st^ century BCE and the 11^th^ century CE. The selected temporal boundaries are framed by significant historical events: the late 1^st^ century BCE marks the onset of the Roman imperial phase, while the 11^th^ century aligns with the reorganisation of rural territories, the phenomenon of *incastellamento* (the creation of castles) and the medieval agricultural revival. This re-evaluation of plant and faunal remains datasets has led to a fresh assessment of transitional crop and animal husbandry practices, shedding light on the agricultural dynamics of a critical period in Italian history.

This study aims to identify the most common domesticated plants/animals and wild resources during the first millennium and to estimate their probability of occurrence. The overall goal is to evaluate the role of these resources in Italian sites in order to assess possible explanations for peasant agricultural choices in terms of diet and economy. The approach used in this assessment is statistical modelling, specifically within a Bayesian framework, of plant and animal remains. Seeds, caryopses and bones are useful proxies for agricultural reconstructions that can be modelled to compare actual distributions in archaeological deposits with our historical assumptions. In particular, Bayesian multilevel modelling has been used to account for overdispersion and class imbalance in the datasets, providing estimates in the form of probabilities. When analysing datasets with assemblages that are subject to sampling bias, a rigorous approach to data analysis is required to avoid overly confident interpretations. In this respect, a major advantage of Bayesian modelling is its explicit ability to incorporate uncertainty into the estimation process. This approach is more intuitive than a frequentist perspective in the sense that estimates are accompanied by credible intervals that provide a range of values within which the true parameter lies.

Finally, this project has tried to comply as much as possible with the guidelines proposed in the FAIR principles [@wilkinsonFAIRGuidingPrinciples2016]. All scripts used for the analyses and datasets are publicly available on GitHub in the digital version of this thesis[^intro-1]. The dataset tables use an intuitive language to facilitate interoperability and integration with future datasets. In the electronic version, it is also possible to use interactive maps by querying the database and to easily access all the bibliographic references of the archaeological contexts. In this way, the project can stimulate future research on the subject and encourage the re-use of otherwise neglected legacy data.

[^intro-1]: URL: <https://github.com/robertoragno/phd>

This thesis is structured as follows—@sec-lit-rev provides an overview of the main debates surrounding (i) the agrarian economy during the first millennium CE, (ii) previous research on Italian bioarchaeology, diet, and climate reconstructions, and (iii) statistical research in archaeology. @sec-materials-bot and @sec-materials-zoo present the materials used for the statistical analyses, as well as sampling and preservation issues. @sec-database describes the structure of the database created to store the raw data. @sec-methods outlines the methodology used in this study, while @sec-archaeobotany and @sec-zooarchaeology present the research findings. @sec-discussion discusses the results and presents hypothetical scenarios for the reconstruction of the historical Italian landscape. The conclusions are presented in @sec-conclusions.
